In [1]:
# Data and Math Libraries
import os
os.environ.setdefault('POLARS_MAX_THREADS', '1')  # avoids a torch/polars native-thread deadlock on macOS
import polars as pl
import numpy as np
from datetime import datetime, timedelta
import random

#Machine Learning Libraries
import torch
import torch.nn as nn 
import torch.optim as optim
import research 
import models

#visualization 
import altair as alt

#data sources
import binance

In [2]:
print(research.__file__)
print([x for x in dir(research) if not x.startswith('_')])

/Users/arezziorietti/Documents/ML Projects/research.py
['BINANCE_TRADE_CSV_COLUMNS', 'BINANCE_VISION_TRADES_URL', 'Dict', 'List', 'OHLC_AGGS', 'Optional', 'Path', 'SEED', 'Tuple', 'Union', 'add_compounding_trades', 'add_equity_curve', 'add_lags', 'add_log_return_features', 'add_model_predictions', 'add_trade_log_returns', 'add_tx_fee', 'add_tx_fees', 'add_tx_fees_log', 'altair', 'auto_reg_corr_matrx', 'batch_train_reg', 'benchmark_linear_models', 'benchmark_reg_model', 'buy_and_hold_performance', 'compare_ts_corr', 'datetime', 'download_trades', 'eval_model_performance', 'get_linear_params', 'get_trade_files', 'init_weights', 'io', 'itertools', 'lag_col_names', 'lag_cols', 'learn_model_trade_pnl', 'learn_model_trades', 'load_ohlc_timeseries', 'load_ohlc_timeseries_range', 'load_timeseries', 'load_timeseries_range', 'log_return', 'log_return_col', 'log_returns_col', 'math', 'model_trade_results', 'models_module', 'nn', 'np', 'npt', 'ohlc_timeseries', 'optim', 'os', 'pl', 'plot', 'plot_column', 'plot_columns', 'plot_distribution', 'plot_dyn_timeseries', 'plot_multiple_lines', 'plot_static_timeseries', 'plt', 'print_model_complexity_ratio', 'print_model_info', 'print_model_params', 'random', 'random_signal_sharpes', 're', 'requests', 'select_best_linear_features', 'set_seed', 'sharpe_annualization_factor', 'sharpe_p_value', 'timedelta', 'timeseries', 'timeseries_split', 'timeseries_train_test_split', 'to_tensor', 'torch', 'total_model_params', 'tqdm', 'train_reg_model', 'walk_forward_eval', 'walk_forward_folds', 'zipfile']

In [3]:
research.set_seed(42)

In [4]:
pl.Config.set_tbl_width_chars(200)
pl.Config.set_fmt_str_lengths(100)
pl.Config.set_tbl_cols(-1)

polars.config.Config

In [5]:
sym = 'BTCUSDT'

hist_data_window = 7 * 4 * 6

time_interval = '1h'

max_lags = 4

forecast_horizon = 1 

annualized_rate = research.sharpe_annualization_factor(time_interval, 365, 24)

# Part 1: BTCUSDT Research

## Download & Load Price Data

In [6]:
# Download hist_data_window days of trade data (skips days already cached)
binance.download_trades(sym, hist_data_window)

Downloading BTCUSDT:   0%|          | 0/168 [00:00<?, ?it/s]

Downloading BTCUSDT:   1%|          | 1/168 [00:00<00:34,  4.78it/s]

Downloading BTCUSDT:   1%|          | 2/168 [00:00<00:24,  6.68it/s]

Downloading BTCUSDT:   2%|▏         | 3/168 [00:00<00:21,  7.74it/s]

Downloading BTCUSDT:   3%|▎         | 5/168 [00:00<00:14, 11.34it/s]

Downloading BTCUSDT:   4%|▍         | 7/168 [00:00<00:15, 10.46it/s]

Downloading BTCUSDT:   5%|▌         | 9/168 [00:01<00:17,  9.15it/s]

Downloading BTCUSDT:   6%|▌         | 10/168 [00:01<00:21,  7.33it/s]

Downloading BTCUSDT:   7%|▋         | 11/168 [00:01<00:26,  5.97it/s]

Downloading BTCUSDT:   7%|▋         | 12/168 [00:01<00:28,  5.49it/s]

Downloading BTCUSDT:   8%|▊         | 13/168 [00:02<00:35,  4.38it/s]

Downloading BTCUSDT:   8%|▊         | 14/168 [00:02<00:37,  4.08it/s]

Downloading BTCUSDT:   9%|▉         | 15/168 [00:02<00:40,  3.78it/s]

Downloading BTCUSDT:  10%|▉         | 16/168 [00:03<00:56,  2.71it/s]

Downloading BTCUSDT:  10%|█         | 17/168 [00:03<01:05,  2.32it/s]

Downloading BTCUSDT:  11%|█         | 18/168 [00:04<00:59,  2.52it/s]

Downloading BTCUSDT:  11%|█▏        | 19/168 [00:04<00:50,  2.94it/s]

Downloading BTCUSDT:  12%|█▏        | 20/168 [00:04<00:46,  3.21it/s]

Downloading BTCUSDT:  12%|█▎        | 21/168 [00:04<00:40,  3.60it/s]

Downloading BTCUSDT:  13%|█▎        | 22/168 [00:05<00:40,  3.60it/s]

Downloading BTCUSDT:  14%|█▎        | 23/168 [00:05<00:36,  3.92it/s]

Downloading BTCUSDT:  14%|█▍        | 24/168 [00:05<00:33,  4.25it/s]

Downloading BTCUSDT:  15%|█▍        | 25/168 [00:05<00:28,  5.09it/s]

Downloading BTCUSDT:  15%|█▌        | 26/168 [00:05<00:24,  5.71it/s]

Downloading BTCUSDT:  16%|█▌        | 27/168 [00:05<00:22,  6.19it/s]

Downloading BTCUSDT:  17%|█▋        | 28/168 [00:06<00:21,  6.37it/s]

Downloading BTCUSDT:  17%|█▋        | 29/168 [00:06<00:21,  6.56it/s]

Downloading BTCUSDT:  18%|█▊        | 30/168 [00:06<00:19,  6.91it/s]

Downloading BTCUSDT:  18%|█▊        | 31/168 [00:06<00:20,  6.72it/s]

Downloading BTCUSDT:  20%|█▉        | 33/168 [00:06<00:14,  9.42it/s]

Downloading BTCUSDT:  21%|██        | 35/168 [00:07<00:19,  6.68it/s]

Downloading BTCUSDT:  21%|██▏       | 36/168 [00:07<00:22,  5.81it/s]

Downloading BTCUSDT:  22%|██▏       | 37/168 [00:07<00:22,  5.71it/s]

Downloading BTCUSDT:  23%|██▎       | 38/168 [00:07<00:23,  5.50it/s]

Downloading BTCUSDT:  23%|██▎       | 39/168 [00:07<00:24,  5.34it/s]

Downloading BTCUSDT:  24%|██▍       | 40/168 [00:08<00:24,  5.21it/s]

Downloading BTCUSDT:  24%|██▍       | 41/168 [00:08<00:26,  4.81it/s]

Downloading BTCUSDT:  25%|██▌       | 42/168 [00:08<00:27,  4.62it/s]

Downloading BTCUSDT:  26%|██▌       | 43/168 [00:08<00:29,  4.24it/s]

Downloading BTCUSDT:  26%|██▌       | 44/168 [00:09<00:29,  4.18it/s]

Downloading BTCUSDT:  27%|██▋       | 45/168 [00:09<00:28,  4.35it/s]

Downloading BTCUSDT:  28%|██▊       | 47/168 [00:09<00:21,  5.72it/s]

Downloading BTCUSDT:  29%|██▊       | 48/168 [00:09<00:21,  5.48it/s]

Downloading BTCUSDT:  29%|██▉       | 49/168 [00:09<00:22,  5.21it/s]

Downloading BTCUSDT:  30%|██▉       | 50/168 [00:10<00:22,  5.26it/s]

Downloading BTCUSDT:  30%|███       | 51/168 [00:10<00:22,  5.31it/s]

Downloading BTCUSDT:  31%|███       | 52/168 [00:10<00:22,  5.13it/s]

Downloading BTCUSDT:  32%|███▏      | 54/168 [00:10<00:16,  7.04it/s]

Downloading BTCUSDT:  33%|███▎      | 55/168 [00:10<00:17,  6.50it/s]

Downloading BTCUSDT:  33%|███▎      | 56/168 [00:11<00:18,  6.18it/s]

Downloading BTCUSDT:  34%|███▍      | 57/168 [00:11<00:18,  5.95it/s]

Downloading BTCUSDT:  35%|███▍      | 58/168 [00:11<00:18,  5.88it/s]

Downloading BTCUSDT:  35%|███▌      | 59/168 [00:11<00:18,  5.86it/s]

Downloading BTCUSDT:  36%|███▋      | 61/168 [00:11<00:14,  7.38it/s]

Downloading BTCUSDT:  37%|███▋      | 62/168 [00:11<00:17,  6.23it/s]

Downloading BTCUSDT:  38%|███▊      | 63/168 [00:12<00:17,  6.11it/s]

Downloading BTCUSDT:  38%|███▊      | 64/168 [00:12<00:16,  6.39it/s]

Downloading BTCUSDT:  39%|███▊      | 65/168 [00:12<00:15,  6.53it/s]

Downloading BTCUSDT:  39%|███▉      | 66/168 [00:12<00:15,  6.55it/s]

Downloading BTCUSDT:  40%|████      | 68/168 [00:12<00:11,  8.67it/s]

Downloading BTCUSDT:  41%|████      | 69/168 [00:12<00:12,  8.17it/s]

Downloading BTCUSDT:  42%|████▏     | 70/168 [00:13<00:13,  7.13it/s]

Downloading BTCUSDT:  42%|████▏     | 71/168 [00:13<00:13,  7.16it/s]

Downloading BTCUSDT:  43%|████▎     | 72/168 [00:13<00:13,  7.06it/s]

Downloading BTCUSDT:  45%|████▍     | 75/168 [00:13<00:08, 10.67it/s]

Downloading BTCUSDT:  46%|████▌     | 77/168 [00:13<00:10,  9.02it/s]

Downloading BTCUSDT:  46%|████▋     | 78/168 [00:13<00:10,  8.59it/s]

Downloading BTCUSDT:  47%|████▋     | 79/168 [00:14<00:10,  8.40it/s]

Downloading BTCUSDT:  48%|████▊     | 80/168 [00:14<00:10,  8.56it/s]

Downloading BTCUSDT:  49%|████▉     | 82/168 [00:14<00:08, 10.29it/s]

Downloading BTCUSDT:  50%|█████     | 84/168 [00:14<00:09,  9.14it/s]

Downloading BTCUSDT:  51%|█████     | 85/168 [00:14<00:09,  9.22it/s]

Downloading BTCUSDT:  51%|█████     | 86/168 [00:14<00:09,  9.00it/s]

Downloading BTCUSDT:  52%|█████▏    | 87/168 [00:14<00:10,  8.02it/s]

Downloading BTCUSDT:  53%|█████▎    | 89/168 [00:15<00:08,  9.02it/s]

Downloading BTCUSDT:  54%|█████▎    | 90/168 [00:15<00:09,  8.66it/s]

Downloading BTCUSDT:  54%|█████▍    | 91/168 [00:15<00:09,  8.23it/s]

Downloading BTCUSDT:  55%|█████▍    | 92/168 [00:15<00:09,  7.79it/s]

Downloading BTCUSDT:  55%|█████▌    | 93/168 [00:15<00:09,  7.74it/s]

Downloading BTCUSDT:  57%|█████▋    | 95/168 [00:15<00:07,  9.88it/s]

Downloading BTCUSDT:  58%|█████▊    | 97/168 [00:16<00:06, 10.51it/s]

Downloading BTCUSDT:  59%|█████▉    | 99/168 [00:16<00:06, 10.42it/s]

Downloading BTCUSDT:  60%|██████    | 101/168 [00:16<00:06, 10.80it/s]

Downloading BTCUSDT:  62%|██████▏   | 104/168 [00:16<00:05, 11.09it/s]

Downloading BTCUSDT:  63%|██████▎   | 106/168 [00:16<00:05, 10.40it/s]

Downloading BTCUSDT:  64%|██████▍   | 108/168 [00:17<00:05, 10.35it/s]

Downloading BTCUSDT:  65%|██████▌   | 110/168 [00:17<00:04, 11.90it/s]

Downloading BTCUSDT:  67%|██████▋   | 112/168 [00:17<00:04, 11.72it/s]

Downloading BTCUSDT:  68%|██████▊   | 114/168 [00:17<00:04, 11.06it/s]

Downloading BTCUSDT:  69%|██████▉   | 116/168 [00:17<00:04, 11.34it/s]

Downloading BTCUSDT:  70%|███████   | 118/168 [00:17<00:04, 11.10it/s]

Downloading BTCUSDT:  71%|███████▏  | 120/168 [00:18<00:04, 11.43it/s]

Downloading BTCUSDT:  73%|███████▎  | 122/168 [00:18<00:03, 11.73it/s]

Downloading BTCUSDT:  74%|███████▍  | 124/168 [00:18<00:03, 12.03it/s]

Downloading BTCUSDT:  75%|███████▌  | 126/168 [00:18<00:03, 11.98it/s]

Downloading BTCUSDT:  76%|███████▌  | 128/168 [00:18<00:03, 10.92it/s]

Downloading BTCUSDT:  77%|███████▋  | 130/168 [00:18<00:03, 11.44it/s]

Downloading BTCUSDT:  79%|███████▊  | 132/168 [00:19<00:03, 11.41it/s]

Downloading BTCUSDT:  80%|███████▉  | 134/168 [00:19<00:04,  7.79it/s]

Downloading BTCUSDT:  80%|████████  | 135/168 [00:19<00:05,  5.77it/s]

Downloading BTCUSDT:  81%|████████  | 136/168 [00:20<00:07,  4.37it/s]

Downloading BTCUSDT:  82%|████████▏ | 137/168 [00:20<00:06,  4.55it/s]

Downloading BTCUSDT:  82%|████████▏ | 138/168 [00:20<00:06,  4.72it/s]

Downloading BTCUSDT:  83%|████████▎ | 139/168 [00:20<00:05,  4.90it/s]

Downloading BTCUSDT:  83%|████████▎ | 140/168 [00:21<00:05,  5.14it/s]

Downloading BTCUSDT:  84%|████████▍ | 141/168 [00:21<00:05,  5.25it/s]

Downloading BTCUSDT:  85%|████████▍ | 142/168 [00:21<00:04,  5.62it/s]

Downloading BTCUSDT:  85%|████████▌ | 143/168 [00:21<00:03,  6.29it/s]

Downloading BTCUSDT:  86%|████████▋ | 145/168 [00:21<00:02,  8.69it/s]

Downloading BTCUSDT:  87%|████████▋ | 146/168 [00:21<00:02,  8.85it/s]

Downloading BTCUSDT:  88%|████████▊ | 148/168 [00:22<00:02,  8.69it/s]

Downloading BTCUSDT:  89%|████████▊ | 149/168 [00:22<00:02,  8.47it/s]

Downloading BTCUSDT:  90%|████████▉ | 151/168 [00:22<00:01, 10.01it/s]

Downloading BTCUSDT:  91%|█████████ | 153/168 [00:22<00:01, 10.53it/s]

Downloading BTCUSDT:  92%|█████████▏| 155/168 [00:22<00:01,  8.82it/s]

Downloading BTCUSDT:  93%|█████████▎| 156/168 [00:22<00:01,  7.49it/s]

Downloading BTCUSDT:  93%|█████████▎| 157/168 [00:23<00:01,  6.44it/s]

Downloading BTCUSDT:  95%|█████████▍| 159/168 [00:23<00:01,  8.14it/s]

Downloading BTCUSDT:  95%|█████████▌| 160/168 [00:23<00:01,  7.45it/s]

Downloading BTCUSDT:  96%|█████████▌| 161/168 [00:23<00:00,  7.39it/s]

Downloading BTCUSDT:  96%|█████████▋| 162/168 [00:23<00:00,  7.11it/s]

Downloading BTCUSDT:  97%|█████████▋| 163/168 [00:23<00:00,  7.01it/s]

Downloading BTCUSDT:  98%|█████████▊| 165/168 [00:24<00:00,  8.85it/s]

Downloading BTCUSDT:  99%|█████████▉| 167/168 [00:24<00:00,  8.99it/s]

Downloading BTCUSDT: 100%|██████████| 168/168 [00:24<00:00,  8.67it/s]

Downloading BTCUSDT: 100%|██████████| 168/168 [00:24<00:00,  6.87it/s]

In [7]:
ts = research.load_ohlc_timeseries(sym, time_interval)
ts

Loading BTCUSDT:   0%|          | 0/169 [00:00<?, ?file/s]

Loading BTCUSDT:   1%|          | 1/169 [00:00<00:40,  4.17file/s]

Loading BTCUSDT:   1%|          | 2/169 [00:00<00:44,  3.77file/s]

Loading BTCUSDT:   2%|▏         | 3/169 [00:00<00:35,  4.70file/s]

Loading BTCUSDT:   2%|▏         | 4/169 [00:00<00:30,  5.38file/s]

Loading BTCUSDT:   4%|▎         | 6/169 [00:00<00:21,  7.68file/s]

Loading BTCUSDT:   4%|▍         | 7/169 [00:01<00:22,  7.12file/s]

Loading BTCUSDT:   5%|▍         | 8/169 [00:01<00:22,  7.15file/s]

Loading BTCUSDT:   5%|▌         | 9/169 [00:01<00:22,  6.97file/s]

Loading BTCUSDT:   6%|▌         | 10/169 [00:01<00:27,  5.77file/s]

Loading BTCUSDT:   7%|▋         | 11/169 [00:02<00:37,  4.22file/s]

Loading BTCUSDT:   7%|▋         | 12/169 [00:02<00:44,  3.56file/s]

Loading BTCUSDT:   8%|▊         | 13/169 [00:02<00:46,  3.37file/s]

Loading BTCUSDT:   8%|▊         | 14/169 [00:03<00:57,  2.70file/s]

Loading BTCUSDT:   9%|▉         | 15/169 [00:03<00:58,  2.62file/s]

Loading BTCUSDT:   9%|▉         | 16/169 [00:04<01:01,  2.50file/s]

Loading BTCUSDT:  10%|█         | 17/169 [00:05<01:36,  1.57file/s]

Loading BTCUSDT:  11%|█         | 18/169 [00:06<01:45,  1.43file/s]

Loading BTCUSDT:  11%|█         | 19/169 [00:06<01:33,  1.61file/s]

Loading BTCUSDT:  12%|█▏        | 20/169 [00:06<01:16,  1.95file/s]

Loading BTCUSDT:  12%|█▏        | 21/169 [00:07<01:09,  2.14file/s]

Loading BTCUSDT:  13%|█▎        | 22/169 [00:07<01:01,  2.38file/s]

Loading BTCUSDT:  14%|█▎        | 23/169 [00:07<00:59,  2.44file/s]

Loading BTCUSDT:  14%|█▍        | 24/169 [00:08<00:55,  2.62file/s]

Loading BTCUSDT:  15%|█▍        | 25/169 [00:08<00:49,  2.94file/s]

Loading BTCUSDT:  15%|█▌        | 26/169 [00:08<00:39,  3.58file/s]

Loading BTCUSDT:  16%|█▌        | 27/169 [00:08<00:35,  3.99file/s]

Loading BTCUSDT:  17%|█▋        | 28/169 [00:09<00:32,  4.30file/s]

Loading BTCUSDT:  17%|█▋        | 29/169 [00:09<00:31,  4.43file/s]

Loading BTCUSDT:  18%|█▊        | 30/169 [00:09<00:30,  4.62file/s]

Loading BTCUSDT:  18%|█▊        | 31/169 [00:09<00:28,  4.83file/s]

Loading BTCUSDT:  19%|█▉        | 32/169 [00:09<00:29,  4.66file/s]

Loading BTCUSDT:  20%|██        | 34/169 [00:10<00:20,  6.50file/s]

Loading BTCUSDT:  21%|██        | 35/169 [00:10<00:25,  5.31file/s]

Loading BTCUSDT:  21%|██▏       | 36/169 [00:10<00:27,  4.78file/s]

Loading BTCUSDT:  22%|██▏       | 37/169 [00:10<00:31,  4.21file/s]

Loading BTCUSDT:  22%|██▏       | 38/169 [00:11<00:32,  4.03file/s]

Loading BTCUSDT:  23%|██▎       | 39/169 [00:11<00:32,  3.99file/s]

Loading BTCUSDT:  24%|██▎       | 40/169 [00:11<00:34,  3.70file/s]

Loading BTCUSDT:  24%|██▍       | 41/169 [00:12<00:34,  3.68file/s]

Loading BTCUSDT:  25%|██▍       | 42/169 [00:12<00:38,  3.28file/s]

Loading BTCUSDT:  25%|██▌       | 43/169 [00:12<00:40,  3.11file/s]

Loading BTCUSDT:  26%|██▌       | 44/169 [00:13<00:46,  2.66file/s]

Loading BTCUSDT:  27%|██▋       | 45/169 [00:13<00:44,  2.78file/s]

Loading BTCUSDT:  27%|██▋       | 46/169 [00:13<00:40,  3.07file/s]

Loading BTCUSDT:  28%|██▊       | 47/169 [00:13<00:32,  3.81file/s]

Loading BTCUSDT:  28%|██▊       | 48/169 [00:14<00:28,  4.21file/s]

Loading BTCUSDT:  29%|██▉       | 49/169 [00:14<00:30,  3.95file/s]

Loading BTCUSDT:  30%|██▉       | 50/169 [00:14<00:32,  3.67file/s]

Loading BTCUSDT:  30%|███       | 51/169 [00:14<00:30,  3.85file/s]

Loading BTCUSDT:  31%|███       | 52/169 [00:15<00:29,  3.99file/s]

Loading BTCUSDT:  31%|███▏      | 53/169 [00:15<00:30,  3.75file/s]

Loading BTCUSDT:  33%|███▎      | 55/169 [00:15<00:22,  5.07file/s]

Loading BTCUSDT:  33%|███▎      | 56/169 [00:16<00:24,  4.58file/s]

Loading BTCUSDT:  34%|███▎      | 57/169 [00:16<00:25,  4.33file/s]

Loading BTCUSDT:  34%|███▍      | 58/169 [00:16<00:27,  4.07file/s]

Loading BTCUSDT:  35%|███▍      | 59/169 [00:16<00:27,  4.03file/s]

Loading BTCUSDT:  36%|███▌      | 60/169 [00:17<00:26,  4.09file/s]

Loading BTCUSDT:  37%|███▋      | 62/169 [00:17<00:20,  5.24file/s]

Loading BTCUSDT:  37%|███▋      | 63/169 [00:17<00:24,  4.31file/s]

Loading BTCUSDT:  38%|███▊      | 64/169 [00:17<00:24,  4.27file/s]

Loading BTCUSDT:  38%|███▊      | 65/169 [00:18<00:23,  4.41file/s]

Loading BTCUSDT:  39%|███▉      | 66/169 [00:18<00:22,  4.54file/s]

Loading BTCUSDT:  40%|███▉      | 67/169 [00:18<00:22,  4.56file/s]

Loading BTCUSDT:  41%|████      | 69/169 [00:18<00:16,  6.02file/s]

Loading BTCUSDT:  41%|████▏     | 70/169 [00:18<00:17,  5.61file/s]

Loading BTCUSDT:  42%|████▏     | 71/169 [00:19<00:19,  5.00file/s]

Loading BTCUSDT:  43%|████▎     | 72/169 [00:19<00:19,  5.06file/s]

Loading BTCUSDT:  43%|████▎     | 73/169 [00:19<00:19,  4.94file/s]

Loading BTCUSDT:  44%|████▍     | 75/169 [00:19<00:13,  7.01file/s]

Loading BTCUSDT:  46%|████▌     | 77/169 [00:20<00:12,  7.09file/s]

Loading BTCUSDT:  46%|████▌     | 78/169 [00:20<00:14,  6.16file/s]

Loading BTCUSDT:  47%|████▋     | 79/169 [00:20<00:15,  5.95file/s]

Loading BTCUSDT:  47%|████▋     | 80/169 [00:20<00:15,  5.80file/s]

Loading BTCUSDT:  48%|████▊     | 81/169 [00:20<00:14,  5.96file/s]

Loading BTCUSDT:  49%|████▉     | 83/169 [00:21<00:11,  7.26file/s]

Loading BTCUSDT:  50%|████▉     | 84/169 [00:21<00:12,  6.66file/s]

Loading BTCUSDT:  50%|█████     | 85/169 [00:21<00:13,  6.22file/s]

Loading BTCUSDT:  51%|█████     | 86/169 [00:21<00:13,  6.30file/s]

Loading BTCUSDT:  51%|█████▏    | 87/169 [00:21<00:13,  6.08file/s]

Loading BTCUSDT:  52%|█████▏    | 88/169 [00:21<00:15,  5.33file/s]

Loading BTCUSDT:  53%|█████▎    | 89/169 [00:22<00:13,  6.07file/s]

Loading BTCUSDT:  53%|█████▎    | 90/169 [00:22<00:12,  6.22file/s]

Loading BTCUSDT:  54%|█████▍    | 91/169 [00:22<00:13,  5.88file/s]

Loading BTCUSDT:  54%|█████▍    | 92/169 [00:22<00:13,  5.65file/s]

Loading BTCUSDT:  55%|█████▌    | 93/169 [00:22<00:13,  5.46file/s]

Loading BTCUSDT:  56%|█████▌    | 94/169 [00:23<00:14,  5.33file/s]

Loading BTCUSDT:  56%|█████▌    | 95/169 [00:23<00:12,  5.76file/s]

Loading BTCUSDT:  57%|█████▋    | 97/169 [00:23<00:08,  8.00file/s]

Loading BTCUSDT:  58%|█████▊    | 98/169 [00:23<00:09,  7.45file/s]

Loading BTCUSDT:  59%|█████▊    | 99/169 [00:23<00:09,  7.61file/s]

Loading BTCUSDT:  59%|█████▉    | 100/169 [00:23<00:09,  7.10file/s]

Loading BTCUSDT:  60%|█████▉    | 101/169 [00:23<00:09,  7.55file/s]

Loading BTCUSDT:  60%|██████    | 102/169 [00:23<00:08,  7.47file/s]

Loading BTCUSDT:  62%|██████▏   | 104/169 [00:24<00:06,  9.66file/s]

Loading BTCUSDT:  62%|██████▏   | 105/169 [00:24<00:08,  7.38file/s]

Loading BTCUSDT:  63%|██████▎   | 106/169 [00:24<00:08,  7.18file/s]

Loading BTCUSDT:  63%|██████▎   | 107/169 [00:24<00:08,  6.95file/s]

Loading BTCUSDT:  64%|██████▍   | 108/169 [00:24<00:08,  7.03file/s]

Loading BTCUSDT:  64%|██████▍   | 109/169 [00:24<00:08,  7.39file/s]

Loading BTCUSDT:  66%|██████▌   | 111/169 [00:25<00:06,  9.30file/s]

Loading BTCUSDT:  66%|██████▋   | 112/169 [00:25<00:06,  8.84file/s]

Loading BTCUSDT:  67%|██████▋   | 113/169 [00:25<00:06,  8.85file/s]

Loading BTCUSDT:  67%|██████▋   | 114/169 [00:25<00:06,  8.59file/s]

Loading BTCUSDT:  68%|██████▊   | 115/169 [00:25<00:07,  7.71file/s]

Loading BTCUSDT:  69%|██████▊   | 116/169 [00:25<00:07,  7.30file/s]

Loading BTCUSDT:  70%|██████▉   | 118/169 [00:25<00:05,  8.75file/s]

Loading BTCUSDT:  70%|███████   | 119/169 [00:26<00:06,  7.56file/s]

Loading BTCUSDT:  71%|███████   | 120/169 [00:26<00:06,  7.84file/s]

Loading BTCUSDT:  72%|███████▏  | 121/169 [00:26<00:05,  8.07file/s]

Loading BTCUSDT:  72%|███████▏  | 122/169 [00:26<00:05,  8.13file/s]

Loading BTCUSDT:  73%|███████▎  | 123/169 [00:26<00:05,  8.39file/s]

Loading BTCUSDT:  73%|███████▎  | 124/169 [00:26<00:05,  8.14file/s]

Loading BTCUSDT:  74%|███████▍  | 125/169 [00:26<00:05,  8.60file/s]

Loading BTCUSDT:  75%|███████▌  | 127/169 [00:27<00:05,  8.34file/s]

Loading BTCUSDT:  76%|███████▌  | 128/169 [00:27<00:05,  7.81file/s]

Loading BTCUSDT:  76%|███████▋  | 129/169 [00:27<00:05,  7.14file/s]

Loading BTCUSDT:  77%|███████▋  | 130/169 [00:27<00:05,  6.83file/s]

Loading BTCUSDT:  78%|███████▊  | 132/169 [00:27<00:03,  9.39file/s]

Loading BTCUSDT:  79%|███████▉  | 134/169 [00:28<00:05,  5.86file/s]

Loading BTCUSDT:  80%|███████▉  | 135/169 [00:28<00:07,  4.81file/s]

Loading BTCUSDT:  80%|████████  | 136/169 [00:29<00:10,  3.29file/s]

Loading BTCUSDT:  81%|████████  | 137/169 [00:29<00:12,  2.56file/s]

Loading BTCUSDT:  82%|████████▏ | 138/169 [00:30<00:11,  2.79file/s]

Loading BTCUSDT:  82%|████████▏ | 139/169 [00:30<00:09,  3.03file/s]

Loading BTCUSDT:  83%|████████▎ | 140/169 [00:30<00:08,  3.25file/s]

Loading BTCUSDT:  83%|████████▎ | 141/169 [00:30<00:08,  3.47file/s]

Loading BTCUSDT:  84%|████████▍ | 142/169 [00:31<00:07,  3.63file/s]

Loading BTCUSDT:  85%|████████▍ | 143/169 [00:31<00:06,  3.90file/s]

Loading BTCUSDT:  85%|████████▌ | 144/169 [00:31<00:05,  4.36file/s]

Loading BTCUSDT:  86%|████████▋ | 146/169 [00:31<00:03,  6.05file/s]

Loading BTCUSDT:  87%|████████▋ | 147/169 [00:31<00:03,  6.08file/s]

Loading BTCUSDT:  88%|████████▊ | 148/169 [00:31<00:03,  6.35file/s]

Loading BTCUSDT:  88%|████████▊ | 149/169 [00:32<00:03,  5.87file/s]

Loading BTCUSDT:  89%|████████▉ | 150/169 [00:32<00:03,  5.83file/s]

Loading BTCUSDT:  89%|████████▉ | 151/169 [00:32<00:02,  6.38file/s]

Loading BTCUSDT:  91%|█████████ | 153/169 [00:32<00:02,  7.93file/s]

Loading BTCUSDT:  91%|█████████ | 154/169 [00:32<00:02,  7.35file/s]

Loading BTCUSDT:  92%|█████████▏| 155/169 [00:32<00:02,  6.84file/s]

Loading BTCUSDT:  92%|█████████▏| 156/169 [00:33<00:02,  5.60file/s]

Loading BTCUSDT:  93%|█████████▎| 157/169 [00:33<00:02,  4.59file/s]

Loading BTCUSDT:  93%|█████████▎| 158/169 [00:33<00:02,  3.97file/s]

Loading BTCUSDT:  95%|█████████▍| 160/169 [00:34<00:01,  5.40file/s]

Loading BTCUSDT:  95%|█████████▌| 161/169 [00:34<00:01,  4.98file/s]

Loading BTCUSDT:  96%|█████████▌| 162/169 [00:34<00:01,  4.97file/s]

Loading BTCUSDT:  96%|█████████▋| 163/169 [00:34<00:01,  4.80file/s]

Loading BTCUSDT:  97%|█████████▋| 164/169 [00:34<00:01,  4.74file/s]

Loading BTCUSDT:  98%|█████████▊| 165/169 [00:35<00:00,  5.34file/s]

Loading BTCUSDT:  99%|█████████▉| 167/169 [00:35<00:00,  7.00file/s]

Loading BTCUSDT:  99%|█████████▉| 168/169 [00:35<00:00,  6.18file/s]

Loading BTCUSDT: 100%|██████████| 169/169 [00:35<00:00,  5.97file/s]

Loading BTCUSDT: 100%|██████████| 169/169 [00:35<00:00,  4.74file/s]

shape: (4_056, 5)
┌─────────────────────┬─────────┬─────────┬─────────┬─────────┐
│ datetime            ┆ open    ┆ high    ┆ low     ┆ close   │
│ ---                 ┆ ---     ┆ ---     ┆ ---     ┆ ---     │
│ datetime[μs]        ┆ f64     ┆ f64     ┆ f64     ┆ f64     │
╞═════════════════════╪═════════╪═════════╪═════════╪═════════╡
│ 2026-01-20 00:00:00 ┆ 92589.6 ┆ 92845.0 ┆ 92320.2 ┆ 92676.1 │
│ 2026-01-20 01:00:00 ┆ 92676.1 ┆ 92840.0 ┆ 92479.1 ┆ 92688.7 │
│ 2026-01-20 02:00:00 ┆ 92688.8 ┆ 92693.4 ┆ 92330.0 ┆ 92518.9 │
│ 2026-01-20 03:00:00 ┆ 92519.0 ┆ 92646.2 ┆ 92200.0 ┆ 92397.0 │
│ 2026-01-20 04:00:00 ┆ 92396.9 ┆ 92440.1 ┆ 91900.0 ┆ 92026.2 │
│ …                   ┆ …       ┆ …       ┆ …       ┆ …       │
│ 2026-07-07 19:00:00 ┆ 63653.6 ┆ 63873.2 ┆ 63351.4 ┆ 63794.9 │
│ 2026-07-07 20:00:00 ┆ 63794.9 ┆ 63874.6 ┆ 63588.5 ┆ 63668.3 │
│ 2026-07-07 21:00:00 ┆ 63668.4 ┆ 63839.9 ┆ 63264.0 ┆ 63399.5 │
│ 2026-07-07 22:00:00 ┆ 63399.5 ┆ 63635.4 ┆ 63177.0 ┆ 63514.9 │
│ 2026-07-07 23:00:00 ┆ 63514.9 ┆ 63679.5 ┆ 63288.0 ┆ 63335.4 │
└─────────────────────┴─────────┴─────────┴─────────┴─────────┘

In [8]:
research.plot_static_timeseries(ts, sym, 'close', time_interval)

/Users/arezziorietti/Documents/ML Projects/research.py:542: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

## Feature Engineering

Build the target (future log return) and auto-regressive lag features.

In [9]:
target = 'close_log_return'
ts = research.add_log_return_features(ts, 'close', forecast_horizon, max_no_lags=max_lags)
ts = ts.drop_nulls()
ts

shape: (4_051, 10)
┌─────────────────────┬─────────┬─────────┬─────────┬─────────┬──────────────────┬────────────────────────┬────────────────────────┬────────────────────────┬────────────────────────┐
│ datetime            ┆ open    ┆ high    ┆ low     ┆ close   ┆ close_log_return ┆ close_log_return_lag_1 ┆ close_log_return_lag_2 ┆ close_log_return_lag_3 ┆ close_log_return_lag_4 │
│ ---                 ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---              ┆ ---                    ┆ ---                    ┆ ---                    ┆ ---                    │
│ datetime[μs]        ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64              ┆ f64                    ┆ f64                    ┆ f64                    ┆ f64                    │
╞═════════════════════╪═════════╪═════════╪═════════╪═════════╪══════════════════╪════════════════════════╪════════════════════════╪════════════════════════╪════════════════════════╡
│ 2026-01-20 05:00:00 ┆ 92026.3 ┆ 92042.1 ┆ 91235.5 ┆ 91590.1 ┆ -0.00475         ┆ -0.004021              ┆ -0.001318              ┆ -0.001834              ┆ 0.000136               │
│ 2026-01-20 06:00:00 ┆ 91590.1 ┆ 91603.8 ┆ 90723.3 ┆ 90894.5 ┆ -0.007624        ┆ -0.00475               ┆ -0.004021              ┆ -0.001318              ┆ -0.001834              │
│ 2026-01-20 07:00:00 ┆ 90894.5 ┆ 91268.8 ┆ 90819.5 ┆ 91136.1 ┆ 0.002655         ┆ -0.007624              ┆ -0.00475               ┆ -0.004021              ┆ -0.001318              │
│ 2026-01-20 08:00:00 ┆ 91136.1 ┆ 91222.0 ┆ 90622.2 ┆ 91078.9 ┆ -0.000628        ┆ 0.002655               ┆ -0.007624              ┆ -0.00475               ┆ -0.004021              │
│ 2026-01-20 09:00:00 ┆ 91078.9 ┆ 91078.9 ┆ 90860.8 ┆ 91002.9 ┆ -0.000835        ┆ -0.000628              ┆ 0.002655               ┆ -0.007624              ┆ -0.00475               │
│ …                   ┆ …       ┆ …       ┆ …       ┆ …       ┆ …                ┆ …                      ┆ …                      ┆ …                      ┆ …                      │
│ 2026-07-07 19:00:00 ┆ 63653.6 ┆ 63873.2 ┆ 63351.4 ┆ 63794.9 ┆ 0.002214         ┆ -0.007994              ┆ 0.003158               ┆ 0.00082                ┆ 0.005861               │
│ 2026-07-07 20:00:00 ┆ 63794.9 ┆ 63874.6 ┆ 63588.5 ┆ 63668.3 ┆ -0.001986        ┆ 0.002214               ┆ -0.007994              ┆ 0.003158               ┆ 0.00082                │
│ 2026-07-07 21:00:00 ┆ 63668.4 ┆ 63839.9 ┆ 63264.0 ┆ 63399.5 ┆ -0.004231        ┆ -0.001986              ┆ 0.002214               ┆ -0.007994              ┆ 0.003158               │
│ 2026-07-07 22:00:00 ┆ 63399.5 ┆ 63635.4 ┆ 63177.0 ┆ 63514.9 ┆ 0.001819         ┆ -0.004231              ┆ -0.001986              ┆ 0.002214               ┆ -0.007994              │
│ 2026-07-07 23:00:00 ┆ 63514.9 ┆ 63679.5 ┆ 63288.0 ┆ 63335.4 ┆ -0.00283         ┆ 0.001819               ┆ -0.004231              ┆ -0.001986              ┆ 0.002214               │
└─────────────────────┴─────────┴─────────┴─────────┴─────────┴──────────────────┴────────────────────────┴────────────────────────┴────────────────────────┴────────────────────────┘

In [10]:
research.plot_distribution(ts, target, no_bins=100)

alt.Chart(...)

In [11]:
# Auto-correlation between the target and its own lags
research.auto_reg_corr_matrx(ts, target, max_lags)

shape: (5, 5)
┌──────────────────┬────────────────────────┬────────────────────────┬────────────────────────┬────────────────────────┐
│ close_log_return ┆ close_log_return_lag_1 ┆ close_log_return_lag_2 ┆ close_log_return_lag_3 ┆ close_log_return_lag_4 │
│ ---              ┆ ---                    ┆ ---                    ┆ ---                    ┆ ---                    │
│ f64              ┆ f64                    ┆ f64                    ┆ f64                    ┆ f64                    │
╞══════════════════╪════════════════════════╪════════════════════════╪════════════════════════╪════════════════════════╡
│ 1.0              ┆ -0.008481              ┆ -0.019831              ┆ 0.005264               ┆ -0.014129              │
│ -0.008481        ┆ 1.0                    ┆ -0.008386              ┆ -0.019874              ┆ 0.005206               │
│ -0.019831        ┆ -0.008386              ┆ 1.0                    ┆ -0.008292              ┆ -0.019843              │
│ 0.005264         ┆ -0.019874              ┆ -0.008292              ┆ 1.0                    ┆ -0.00837               │
│ -0.014129        ┆ 0.005206               ┆ -0.019843              ┆ -0.00837               ┆ 1.0                    │
└──────────────────┴────────────────────────┴────────────────────────┴────────────────────────┴────────────────────────┘

## Benchmark Linear Models

Try every combination of up to 3 lag features and rank by annualized Sharpe.

In [12]:
feature_pool = [f'{target}_lag_{i}' for i in range(1, max_lags + 1)]
btc_benchmark = research.benchmark_linear_models(
    ts, target, feature_pool, annualized_rate, max_no_features=3, loss=nn.L1Loss()
)
btc_benchmark

shape: (14, 18)
┌───────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ features  ┆ target   ┆ no_trade ┆ win_rate ┆ avg_win  ┆ avg_loss ┆ best_tra ┆ worst_tr ┆ ev       ┆ std      ┆ total_lo ┆ compound ┆ max_draw ┆ equity_t ┆ equity_p ┆ sharpe   ┆ weights  ┆ biases   │
│ ---       ┆ ---      ┆ s        ┆ ---      ┆ ---      ┆ ---      ┆ de       ┆ ade      ┆ ---      ┆ ---      ┆ g_return ┆ _return  ┆ down     ┆ rough    ┆ eak      ┆ ---      ┆ ---      ┆ ---      │
│ str       ┆ str      ┆ ---      ┆ f64      ┆ f64      ┆ f64      ┆ ---      ┆ ---      ┆ f64      ┆ f64      ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ f64      ┆ str      ┆ str      │
│           ┆          ┆ i64      ┆          ┆          ┆          ┆ f64      ┆ f64      ┆          ┆          ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆          ┆          ┆          │
╞═══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╡
│ close_log ┆ close_lo ┆ 1013     ┆ 0.530109 ┆ 0.003668 ┆ -0.00321 ┆ 0.049699 ┆ -0.02293 ┆ 0.000434 ┆ 0.005257 ┆ 0.439939 ┆ 1.552613 ┆ -0.08753 ┆ -0.05361 ┆ 0.442769 ┆ 7.731603 ┆ [-0.0463 ┆ -1.15588 │
│ _return_l ┆ g_return ┆          ┆          ┆          ┆ 4        ┆          ┆ 6        ┆          ┆          ┆          ┆          ┆ 1        ┆          ┆          ┆          ┆ 8382 -0. ┆ 48200365 │
│ ag_2,clos ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ 02816361 ┆ 901e-05  │
│ e_log_ret ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ ]        ┆          │
│ urn_lag_4 ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
│ close_log ┆ close_lo ┆ 1013     ┆ 0.529121 ┆ 0.003589 ┆ -0.00330 ┆ 0.049699 ┆ -0.02395 ┆ 0.000343 ┆ 0.005264 ┆ 0.347159 ┆ 1.415041 ┆ -0.08312 ┆ 0.000136 ┆ 0.349989 ┆ 6.093207 ┆ [-0.0246 ┆ -1.17382 │
│ _return_l ┆ g_return ┆          ┆          ┆          ┆ 5        ┆          ┆ 2        ┆          ┆          ┆          ┆          ┆ 2        ┆          ┆          ┆          ┆ 9324 -0. ┆ 63310689 │
│ ag_1,clos ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ 06081564 ┆ 945e-05  │
│ e_log_ret ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ ]        ┆          │
│ urn_lag_2 ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
│ close_log ┆ close_lo ┆ 1013     ┆ 0.542942 ┆ 0.003487 ┆ -0.00341 ┆ 0.024953 ┆ -0.04969 ┆ 0.000332 ┆ 0.005265 ┆ 0.336147 ┆ 1.399545 ┆ -0.06763 ┆ 0.002709 ┆ 0.351881 ┆ 5.899155 ┆ [-0.0407 ┆ -3.80322 │
│ _return_l ┆ g_return ┆          ┆          ┆          ┆ 6        ┆          ┆ 9        ┆          ┆          ┆          ┆          ┆ 3        ┆          ┆          ┆          ┆ 5581 -0. ┆ 42173358 │
│ ag_2,clos ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ 02804954 ┆ 1e-06    │
│ e_log_ret ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ ]        ┆          │
│ urn_lag_3 ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
│ close_log ┆ close_lo ┆ 1013     ┆ 0.538993 ┆ 0.003482 ┆ -0.00342 ┆ 0.024953 ┆ -0.04969 ┆ 0.000299 ┆ 0.005267 ┆ 0.302559 ┆ 1.353317 ┆ -0.13126 ┆ -0.07329 ┆ 0.328924 ┆ 5.3077   ┆ [-0.0288 ┆ -3.50622 │
│ _return_l ┆ g_return ┆          ┆          ┆          ┆ 3        ┆          ┆ 9        ┆          ┆          ┆          ┆          ┆ 3        ┆ 3        ┆          ┆          ┆ 7406 -0. ┆ 86769971 │
│ ag_1,clos ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ 02253534 ┆ 25e-05   │
│ e_log_ret ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ -0.03189 ┆          │
│ urn_lag_3 ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ 928]     ┆          │
│ ,close_lo ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
│ g_return_ ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
│ lag_4     ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
│ close_log ┆ close_lo ┆ 1013     ┆ 0.521224 ┆ 0.00356  ┆ -0.00334 ┆ 0.024953 ┆ -0.04969 ┆ 0.000256 ┆ 0.005269 ┆ 0.259543 ┆ 1.296337 ┆ -0.10401 ┆ -0.03449 ┆ 0.308145 ┆ 4.55115  ┆ [-0.0129 ┆ -1.73140 │
│ _return_l ┆ g_return ┆          ┆          ┆          ┆          ┆          ┆ 9        ┆          ┆          ┆          ┆          ┆ 4        ┆ 4        ┆          ┆          ┆ 2978 -0. ┆ 68827545 │
│ ag_3,clos ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ 03342096 ┆ 27e-05   │
│ e_log_ret ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ ]        ┆          │
│ urn_lag_4 ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
│ …         ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        │
│ close_log ┆ close_lo ┆ 1013     ┆ 0.538006 ┆ 0.003323 ┆ -0.00360 ┆ 0.049699 ┆ -0.02395 ┆ 0.000121 ┆ 0.005274 ┆ 0.1225   ┆ 1.130319 ┆ -0.15704 ┆ -0.00396 ┆ 0.207991 ┆ 2.146096 ┆ [-0.0399 ┆ -4.30505 │
│ _return_l ┆ g_return ┆          ┆          ┆          ┆ 8        ┆          ┆ 2        ┆          ┆          ┆          ┆          ┆ 9        ┆ 1        ┆          ┆          ┆ 5011]    ┆ 82462456 │
│ ag_1      ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ 08e-05   │
│ close_log ┆ close_lo ┆ 1013     ┆ 0.498519 ┆ 0.00356  ┆ -0.00335 ┆ 0.049699 ┆ -0.02495 ┆ 0.000095 ┆ 0.005274 ┆ 0.095937 ┆ 1.10069  ┆ -0.16628 ┆ -0.05664 ┆ 0.214886 ┆ 1.680565 ┆ [-0.0330 ┆ -2.59985 │
│ _return_l ┆ g_return ┆          ┆          ┆          ┆          ┆          ┆ 3        ┆          ┆          ┆          ┆          ┆ 5        ┆ 5        ┆          ┆          ┆ 9952]    ┆ 48153438 │
│ ag_4      ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ 605e-05  │
│ close_log ┆ close_lo ┆ 1013     ┆ 0.535044 ┆ 0.00329  ┆ -0.00364 ┆ 0.024953 ┆ -0.04969 ┆ 0.000066 ┆ 0.005275 ┆ 0.066889 ┆ 1.069177 ┆ -0.17860 ┆ 0.001861 ┆ 0.218239 ┆ 1.171625 ┆ [-0.0464 ┆ -1.82580 │
│ _return_l ┆ g_return ┆          ┆          ┆          ┆ 4        ┆          ┆ 9        ┆          ┆          ┆          ┆          ┆ 2        ┆          ┆          ┆          ┆ 4156 -0. ┆ 77034261 │
│ ag_1,clos ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ 04747161 ┆ 078e-05  │
│ e_log_ret ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ -0.01680 ┆          │
│ urn_lag_2 ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ 875]     ┆          │
│ ,close_lo ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
│ g_return_ ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
│ lag_3     ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
│ close_log ┆ close_lo ┆ 1013     ┆ 0.529121 ┆ 0.003287 ┆ -0.00364 ┆ 0.024953 ┆ -0.04969 ┆ 0.000024 ┆ 0.005275 ┆ 0.023958 ┆ 1.024247 ┆ -0.18270 ┆ -0.14577 ┆ 0.12965  ┆ 0.419617 ┆ [-0.0507 ┆ -2.55640 │
│ _return_l ┆ g_return ┆          ┆          ┆          ┆ 3        ┆          ┆ 9        ┆          ┆          ┆          ┆          ┆ 1        ┆ 4        ┆          ┆          ┆ 8843 -0. ┆ 55249560 │
│ ag_1,clos ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ 02314105 ┆ 624e-05  │
│ e_log_ret ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ ]        ┆          │
│ urn_lag_4 ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
│ close_log ┆ close_lo ┆ 1013     ┆ 0.522211 ┆ 0.003308 ┆ -0.00361 ┆ 0.024953 ┆ -0.04969 ┆ 3.2458e- ┆ 0.005275 ┆ 0.000329 ┆ 1.000329 ┆ -0.21148 ┆ -0.01701 ┆ 0.194465 ┆ 0.005759 ┆ [-0.0413 ┆ -4.18863 │
│ _return_l ┆ g_return ┆          ┆          ┆          ┆ 5        ┆          ┆ 9        ┆ 7        ┆          ┆          ┆          ┆ 3        ┆ 9        ┆          ┆          ┆ 6413 -0. ┆ 96502377 │
│ ag_1,clos ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ 00907034 ┆ 465e-05  │
│ e_log_ret ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ ]        ┆          │
│ urn_lag_3 ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
└───────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┘

In [13]:
btc_best = btc_benchmark.row(0, named=True)
btc_best_features = btc_best['features'].split(',')
btc_best_features

['close_log_return_lag_2', 'close_log_return_lag_4']

## Best Model: Trade-Level Performance

In [14]:
btc_model = models.LinearModel(len(btc_best_features))
btc_model_trades = research.learn_model_trades(ts, btc_best_features, target, btc_model, loss=nn.L1Loss())
research.plot_column(btc_model_trades, 'equity_curve')

alt.Chart(...)

## Add Transaction Fees

In [15]:
maker_fee = 0.00045
taker_fee = 0.00045
btc_model_trades = research.add_tx_fees_log(btc_model_trades, maker_fee, taker_fee)
research.plot_column(btc_model_trades, 'equity_curve_net_taker')

alt.Chart(...)

## Save Model

In [16]:
torch.save(btc_model.state_dict(), 'BTCUSDT_model_weights.pth')
print(f"Saved BTCUSDT model with features {btc_best_features}")

Saved BTCUSDT model with features ['close_log_return_lag_2', 'close_log_return_lag_4']

## Out-of-Sample Validation (Walk-Forward)

The benchmark above picked the "best" feature combo by scanning every lag combination and choosing whichever had the highest Sharpe on a single holdout split. With that many combinations tried, a good-looking Sharpe can show up by luck alone (data snooping) — it doesn't prove the model has real predictive power.

This section fixes that: `walk_forward_eval` re-runs feature selection and training on rolling windows where each fold's test period was never seen during that fold's selection or training. The folds are then stitched into one continuous out-of-sample equity curve, which we compare against two baselines: buy-and-hold, and a random coin-flip trading signal (the null hypothesis of "no skill at all").

In [17]:
btc_wf_folds, btc_oos_y_test, btc_oos_y_hat = research.walk_forward_eval(
    ts, target, feature_pool, annualized_rate, n_folds=5, loss=nn.L1Loss()
)
btc_wf_folds

shape: (5, 18)
┌───────────┬───────────┬───────────┬──────────┬──────────┬───────────┬───────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────┬──────────┐
│ features  ┆ target    ┆ no_trades ┆ win_rate ┆ avg_win  ┆ avg_loss  ┆ best_trad ┆ worst_tr ┆ ev       ┆ std      ┆ total_lo ┆ compound ┆ max_draw ┆ equity_t ┆ equity_p ┆ sharpe   ┆ fold ┆ no_test_ │
│ ---       ┆ ---       ┆ ---       ┆ ---      ┆ ---      ┆ ---       ┆ e         ┆ ade      ┆ ---      ┆ ---      ┆ g_return ┆ _return  ┆ down     ┆ rough    ┆ eak      ┆ ---      ┆ ---  ┆ obs      │
│ str       ┆ str       ┆ i64       ┆ f64      ┆ f64      ┆ f64       ┆ ---       ┆ ---      ┆ f64      ┆ f64      ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ f64      ┆ i64  ┆ ---      │
│           ┆           ┆           ┆          ┆          ┆           ┆ f64       ┆ f64      ┆          ┆          ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆          ┆      ┆ i64      │
╞═══════════╪═══════════╪═══════════╪══════════╪══════════╪═══════════╪═══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════╪══════════╡
│ close_log ┆ close_log ┆ 405       ┆ 0.555556 ┆ 0.002401 ┆ -0.002769 ┆ 0.013149  ┆ -0.01691 ┆ 0.000103 ┆ 0.003568 ┆ 0.041821 ┆ 1.042708 ┆ -0.05875 ┆ -0.01362 ┆ 0.07016  ┆ 2.708611 ┆ 0    ┆ 405      │
│ _return_l ┆ _return   ┆           ┆          ┆          ┆           ┆           ┆ 2        ┆          ┆          ┆          ┆          ┆ 7        ┆ 1        ┆          ┆          ┆      ┆          │
│ ag_1,clos ┆           ┆           ┆          ┆          ┆           ┆           ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆      ┆          │
│ e_log_ret ┆           ┆           ┆          ┆          ┆           ┆           ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆      ┆          │
│ urn_lag_2 ┆           ┆           ┆          ┆          ┆           ┆           ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆      ┆          │
│ ,close_lo ┆           ┆           ┆          ┆          ┆           ┆           ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆      ┆          │
│ g_return_ ┆           ┆           ┆          ┆          ┆           ┆           ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆      ┆          │
│ lag_3     ┆           ┆           ┆          ┆          ┆           ┆           ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆      ┆          │
│ close_log ┆ close_log ┆ 405       ┆ 0.516049 ┆ 0.002112 ┆ -0.002239 ┆ 0.016465  ┆ -0.02039 ┆ 0.000006 ┆ 0.003335 ┆ 0.002531 ┆ 1.002534 ┆ -0.05786 ┆ -0.03370 ┆ 0.054314 ┆ 0.175379 ┆ 1    ┆ 405      │
│ _return_l ┆ _return   ┆           ┆          ┆          ┆           ┆           ┆ 5        ┆          ┆          ┆          ┆          ┆ 4        ┆ 3        ┆          ┆          ┆      ┆          │
│ ag_2      ┆           ┆           ┆          ┆          ┆           ┆           ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆      ┆          │
│ close_log ┆ close_log ┆ 405       ┆ 0.518519 ┆ 0.002634 ┆ -0.0029   ┆ 0.017843  ┆ -0.01871 ┆ -0.00003 ┆ 0.004169 ┆ -0.01237 ┆ 0.987704 ┆ -0.10113 ┆ -0.07940 ┆ 0.021733 ┆ -0.68577 ┆ 2    ┆ 405      │
│ _return_l ┆ _return   ┆           ┆          ┆          ┆           ┆           ┆ 8        ┆ 1        ┆          ┆ 2        ┆          ┆ 8        ┆ 5        ┆          ┆ 3        ┆      ┆          │
│ ag_2,clos ┆           ┆           ┆          ┆          ┆           ┆           ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆      ┆          │
│ e_log_ret ┆           ┆           ┆          ┆          ┆           ┆           ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆      ┆          │
│ urn_lag_4 ┆           ┆           ┆          ┆          ┆           ┆           ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆      ┆          │
│ close_log ┆ close_log ┆ 405       ┆ 0.520988 ┆ 0.003757 ┆ -0.003632 ┆ 0.02371   ┆ -0.02293 ┆ 0.000218 ┆ 0.005405 ┆ 0.088142 ┆ 1.092143 ┆ -0.06748 ┆ -0.02000 ┆ 0.113039 ┆ 3.768484 ┆ 3    ┆ 405      │
│ _return_l ┆ _return   ┆           ┆          ┆          ┆           ┆           ┆ 6        ┆          ┆          ┆          ┆          ┆ 5        ┆ 6        ┆          ┆          ┆      ┆          │
│ ag_2,clos ┆           ┆           ┆          ┆          ┆           ┆           ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆      ┆          │
│ e_log_ret ┆           ┆           ┆          ┆          ┆           ┆           ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆      ┆          │
│ urn_lag_3 ┆           ┆           ┆          ┆          ┆           ┆           ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆      ┆          │
│ close_log ┆ close_log ┆ 406       ┆ 0.534483 ┆ 0.00352  ┆ -0.003154 ┆ 0.049699  ┆ -0.01487 ┆ 0.000413 ┆ 0.005338 ┆ 0.167819 ┆ 1.182722 ┆ -0.07217 ┆ -0.00276 ┆ 0.174373 ┆ 7.247375 ┆ 4    ┆ 406      │
│ _return_l ┆ _return   ┆           ┆          ┆          ┆           ┆           ┆ 1        ┆          ┆          ┆          ┆          ┆ 7        ┆          ┆          ┆          ┆      ┆          │
│ ag_2,clos ┆           ┆           ┆          ┆          ┆           ┆           ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆      ┆          │
│ e_log_ret ┆           ┆           ┆          ┆          ┆           ┆           ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆      ┆          │
│ urn_lag_4 ┆           ┆           ┆          ┆          ┆           ┆           ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆      ┆          │
└───────────┴───────────┴───────────┴──────────┴──────────┴───────────┴───────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────┴──────────┘

In [18]:
# Stitched-together out-of-sample performance across all folds
btc_oos_perf = research.eval_model_performance(btc_oos_y_test, btc_oos_y_hat, feature_pool, target, annualized_rate)
btc_oos_perf

{'features': 'close_log_return_lag_1,close_log_return_lag_2,close_log_return_lag_3,close_log_return_lag_4',
 'target': 'close_log_return',
 'no_trades': 2026,
 'win_rate': 0.5291214215202369,
 'avg_win': 0.0028836563780214926,
 'avg_loss': -0.0029385104119318915,
 'best_trade': 0.04969850182533264,
 'worst_trade': -0.022935960441827774,
 'ev': 0.0001421227562961576,
 'std': 0.004447606857866049,
 'total_log_return': 0.28794071078300476,
 'compound_return': np.float64(1.3336782290413343),
 'max_drawdown': -0.13118776679039001,
 'equity_trough': -0.03505219146609306,
 'equity_peak': 0.2944944500923157,
 'sharpe': np.float64(2.990813163078893)}

### Baselines: Buy & Hold and a Random-Signal Null Distribution

In [19]:
btc_bh_perf = research.buy_and_hold_performance(btc_oos_y_test, annualized_rate)
btc_bh_perf

{'strategy': 'buy_and_hold',
 'no_periods': 2026,
 'total_log_return': -0.17530666291713715,
 'compound_return': 0.8391996026039124,
 'std': 0.004447938408702612,
 'max_drawdown': -0.3479048013687134,
 'sharpe': -1.8207580714737432}

In [20]:
# Null distribution: 1000 random +1/-1 signals against the SAME realized OOS returns.
# If our model has no real edge, its Sharpe should look like a typical draw from this distribution.
btc_null_sharpes = research.random_signal_sharpes(btc_oos_y_test, annualized_rate, n_trials=1000, seed=42)
btc_p_value = research.sharpe_p_value(btc_oos_perf['sharpe'], btc_null_sharpes)

print(f"BTCUSDT OOS model Sharpe:      {btc_oos_perf['sharpe']:.2f}")
print(f"BTCUSDT Buy & Hold Sharpe:     {btc_bh_perf['sharpe']:.2f}")
print(f"Random-signal null Sharpe:     mean={btc_null_sharpes.mean():.2f}, std={btc_null_sharpes.std():.2f}")
print(f"P(random signal Sharpe >= model OOS Sharpe): {btc_p_value:.3f}")

BTCUSDT OOS model Sharpe:      2.99
BTCUSDT Buy & Hold Sharpe:     -1.82
Random-signal null Sharpe:     mean=-0.07, std=2.10
P(random signal Sharpe >= model OOS Sharpe): 0.068

In [21]:
import matplotlib.pyplot as plt

btc_oos_trades = research.model_trade_results(btc_oos_y_test, btc_oos_y_hat)
btc_bh_equity_curve = np.cumsum(btc_oos_y_test.numpy().flatten())

plt.figure(figsize=(12, 6))
plt.plot(btc_oos_trades['equity_curve'], label='Model (walk-forward OOS)')
plt.plot(btc_bh_equity_curve, label='Buy & Hold')
plt.title('BTCUSDT: Out-of-Sample Equity Curve vs Buy & Hold')
plt.xlabel('Period (stitched across folds)')
plt.ylabel('Cumulative Log Return')
plt.legend()
plt.tight_layout()
plt.show()

/var/folders/69/1t3g51kj5y96vspv1zh9f1x40000gn/T/ipykernel_30504/2974186181.py:14: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

# Part 2: ETHUSDT Research

Repeat the exact same research pipeline on a second asset (ETHUSDT) so we're not overfitting our conclusions to a single symbol.

## Download & Load Price Data

In [22]:
sym = 'ETHUSDT'
binance.download_trades(sym, hist_data_window)

Downloading ETHUSDT:   0%|          | 0/168 [00:00<?, ?it/s]

Downloading ETHUSDT:   1%|          | 1/168 [00:00<00:49,  3.34it/s]

Downloading ETHUSDT:   1%|          | 2/168 [00:00<00:41,  4.03it/s]

Downloading ETHUSDT:   2%|▏         | 3/168 [00:00<00:36,  4.46it/s]

Downloading ETHUSDT:   3%|▎         | 5/168 [00:00<00:25,  6.42it/s]

Downloading ETHUSDT:   4%|▎         | 6/168 [00:01<00:29,  5.56it/s]

Downloading ETHUSDT:   4%|▍         | 7/168 [00:01<00:29,  5.42it/s]

Downloading ETHUSDT:   5%|▍         | 8/168 [00:01<00:29,  5.43it/s]

Downloading ETHUSDT:   5%|▌         | 9/168 [00:01<00:33,  4.81it/s]

Downloading ETHUSDT:   6%|▌         | 10/168 [00:02<00:42,  3.68it/s]

Downloading ETHUSDT:   7%|▋         | 11/168 [00:02<00:53,  2.96it/s]

Downloading ETHUSDT:   7%|▋         | 12/168 [00:03<00:59,  2.62it/s]

Downloading ETHUSDT:   8%|▊         | 13/168 [00:03<01:11,  2.16it/s]

Downloading ETHUSDT:   8%|▊         | 14/168 [00:04<01:15,  2.05it/s]

Downloading ETHUSDT:   9%|▉         | 15/168 [00:04<01:15,  2.02it/s]

Downloading ETHUSDT:  10%|▉         | 16/168 [00:05<01:33,  1.62it/s]

Downloading ETHUSDT:  10%|█         | 17/168 [00:06<01:44,  1.44it/s]

Downloading ETHUSDT:  11%|█         | 18/168 [00:07<01:32,  1.62it/s]

Downloading ETHUSDT:  11%|█▏        | 19/168 [00:07<01:16,  1.95it/s]

Downloading ETHUSDT:  12%|█▏        | 20/168 [00:07<01:08,  2.15it/s]

Downloading ETHUSDT:  12%|█▎        | 21/168 [00:08<01:01,  2.38it/s]

Downloading ETHUSDT:  13%|█▎        | 22/168 [00:08<01:00,  2.41it/s]

Downloading ETHUSDT:  14%|█▎        | 23/168 [00:08<00:54,  2.65it/s]

Downloading ETHUSDT:  14%|█▍        | 24/168 [00:09<00:49,  2.89it/s]

Downloading ETHUSDT:  15%|█▍        | 25/168 [00:09<00:40,  3.53it/s]

Downloading ETHUSDT:  15%|█▌        | 26/168 [00:09<00:38,  3.68it/s]

Downloading ETHUSDT:  16%|█▌        | 27/168 [00:09<00:36,  3.87it/s]

Downloading ETHUSDT:  17%|█▋        | 28/168 [00:09<00:34,  4.04it/s]

Downloading ETHUSDT:  17%|█▋        | 29/168 [00:10<00:33,  4.21it/s]

Downloading ETHUSDT:  18%|█▊        | 30/168 [00:10<00:31,  4.37it/s]

Downloading ETHUSDT:  18%|█▊        | 31/168 [00:10<00:30,  4.56it/s]

Downloading ETHUSDT:  20%|█▉        | 33/168 [00:10<00:20,  6.45it/s]

Downloading ETHUSDT:  20%|██        | 34/168 [00:10<00:24,  5.55it/s]

Downloading ETHUSDT:  21%|██        | 35/168 [00:11<00:26,  4.93it/s]

Downloading ETHUSDT:  21%|██▏       | 36/168 [00:11<00:32,  4.05it/s]

Downloading ETHUSDT:  22%|██▏       | 37/168 [00:11<00:32,  4.06it/s]

Downloading ETHUSDT:  23%|██▎       | 38/168 [00:12<00:33,  3.92it/s]

Downloading ETHUSDT:  23%|██▎       | 39/168 [00:12<00:35,  3.68it/s]

Downloading ETHUSDT:  24%|██▍       | 40/168 [00:12<00:35,  3.60it/s]

Downloading ETHUSDT:  24%|██▍       | 41/168 [00:13<00:38,  3.34it/s]

Downloading ETHUSDT:  25%|██▌       | 42/168 [00:13<00:40,  3.12it/s]

Downloading ETHUSDT:  26%|██▌       | 43/168 [00:13<00:44,  2.80it/s]

Downloading ETHUSDT:  26%|██▌       | 44/168 [00:14<00:43,  2.87it/s]

Downloading ETHUSDT:  27%|██▋       | 45/168 [00:14<00:39,  3.09it/s]

Downloading ETHUSDT:  28%|██▊       | 47/168 [00:14<00:28,  4.21it/s]

Downloading ETHUSDT:  29%|██▊       | 48/168 [00:15<00:31,  3.84it/s]

Downloading ETHUSDT:  29%|██▉       | 49/168 [00:15<00:32,  3.69it/s]

Downloading ETHUSDT:  30%|██▉       | 50/168 [00:15<00:30,  3.87it/s]

Downloading ETHUSDT:  30%|███       | 51/168 [00:15<00:28,  4.05it/s]

Downloading ETHUSDT:  31%|███       | 52/168 [00:16<00:30,  3.84it/s]

Downloading ETHUSDT:  32%|███▏      | 54/168 [00:16<00:21,  5.21it/s]

Downloading ETHUSDT:  33%|███▎      | 55/168 [00:16<00:25,  4.43it/s]

Downloading ETHUSDT:  33%|███▎      | 56/168 [00:16<00:26,  4.21it/s]

Downloading ETHUSDT:  34%|███▍      | 57/168 [00:17<00:27,  4.07it/s]

Downloading ETHUSDT:  35%|███▍      | 58/168 [00:17<00:28,  3.87it/s]

Downloading ETHUSDT:  35%|███▌      | 59/168 [00:17<00:26,  4.04it/s]

Downloading ETHUSDT:  36%|███▋      | 61/168 [00:17<00:20,  5.20it/s]

Downloading ETHUSDT:  37%|███▋      | 62/168 [00:18<00:24,  4.35it/s]

Downloading ETHUSDT:  38%|███▊      | 63/168 [00:18<00:24,  4.36it/s]

Downloading ETHUSDT:  38%|███▊      | 64/168 [00:18<00:22,  4.56it/s]

Downloading ETHUSDT:  39%|███▊      | 65/168 [00:18<00:22,  4.63it/s]

Downloading ETHUSDT:  39%|███▉      | 66/168 [00:19<00:21,  4.69it/s]

Downloading ETHUSDT:  40%|████      | 68/168 [00:19<00:16,  6.23it/s]

Downloading ETHUSDT:  41%|████      | 69/168 [00:19<00:16,  5.99it/s]

Downloading ETHUSDT:  42%|████▏     | 70/168 [00:19<00:19,  5.14it/s]

Downloading ETHUSDT:  42%|████▏     | 71/168 [00:19<00:19,  5.00it/s]

Downloading ETHUSDT:  43%|████▎     | 72/168 [00:20<00:20,  4.79it/s]

Downloading ETHUSDT:  44%|████▍     | 74/168 [00:20<00:13,  6.80it/s]

Downloading ETHUSDT:  45%|████▌     | 76/168 [00:20<00:13,  6.91it/s]

Downloading ETHUSDT:  46%|████▌     | 77/168 [00:20<00:15,  5.89it/s]

Downloading ETHUSDT:  46%|████▋     | 78/168 [00:21<00:16,  5.47it/s]

Downloading ETHUSDT:  47%|████▋     | 79/168 [00:21<00:16,  5.40it/s]

Downloading ETHUSDT:  48%|████▊     | 80/168 [00:21<00:15,  5.70it/s]

Downloading ETHUSDT:  48%|████▊     | 81/168 [00:21<00:13,  6.38it/s]

Downloading ETHUSDT:  49%|████▉     | 82/168 [00:21<00:12,  6.72it/s]

Downloading ETHUSDT:  49%|████▉     | 83/168 [00:21<00:14,  5.97it/s]

Downloading ETHUSDT:  50%|█████     | 84/168 [00:22<00:15,  5.27it/s]

Downloading ETHUSDT:  51%|█████     | 85/168 [00:22<00:15,  5.40it/s]

Downloading ETHUSDT:  51%|█████     | 86/168 [00:22<00:15,  5.38it/s]

Downloading ETHUSDT:  52%|█████▏    | 87/168 [00:22<00:16,  4.94it/s]

Downloading ETHUSDT:  52%|█████▏    | 88/168 [00:22<00:14,  5.60it/s]

Downloading ETHUSDT:  53%|█████▎    | 89/168 [00:22<00:13,  5.82it/s]

Downloading ETHUSDT:  54%|█████▎    | 90/168 [00:23<00:13,  5.61it/s]

Downloading ETHUSDT:  54%|█████▍    | 91/168 [00:23<00:13,  5.63it/s]

Downloading ETHUSDT:  55%|█████▍    | 92/168 [00:23<00:13,  5.52it/s]

Downloading ETHUSDT:  55%|█████▌    | 93/168 [00:23<00:13,  5.48it/s]

Downloading ETHUSDT:  56%|█████▌    | 94/168 [00:23<00:12,  6.15it/s]

Downloading ETHUSDT:  57%|█████▋    | 96/168 [00:23<00:08,  8.92it/s]

Downloading ETHUSDT:  58%|█████▊    | 98/168 [00:24<00:08,  8.57it/s]

Downloading ETHUSDT:  59%|█████▉    | 99/168 [00:24<00:08,  7.81it/s]

Downloading ETHUSDT:  60%|█████▉    | 100/168 [00:24<00:08,  8.00it/s]

Downloading ETHUSDT:  61%|██████    | 102/168 [00:24<00:06,  9.75it/s]

Downloading ETHUSDT:  62%|██████▏   | 104/168 [00:24<00:07,  8.90it/s]

Downloading ETHUSDT:  62%|██████▎   | 105/168 [00:25<00:07,  8.89it/s]

Downloading ETHUSDT:  63%|██████▎   | 106/168 [00:25<00:07,  8.32it/s]

Downloading ETHUSDT:  64%|██████▎   | 107/168 [00:25<00:07,  8.06it/s]

Downloading ETHUSDT:  64%|██████▍   | 108/168 [00:25<00:07,  8.29it/s]

Downloading ETHUSDT:  65%|██████▌   | 110/168 [00:25<00:05,  9.92it/s]

Downloading ETHUSDT:  66%|██████▌   | 111/168 [00:25<00:05,  9.83it/s]

Downloading ETHUSDT:  67%|██████▋   | 112/168 [00:25<00:05,  9.62it/s]

Downloading ETHUSDT:  67%|██████▋   | 113/168 [00:25<00:05,  9.51it/s]

Downloading ETHUSDT:  68%|██████▊   | 114/168 [00:25<00:05,  9.05it/s]

Downloading ETHUSDT:  68%|██████▊   | 115/168 [00:26<00:06,  8.69it/s]

Downloading ETHUSDT:  70%|██████▉   | 117/168 [00:26<00:04, 10.22it/s]

Downloading ETHUSDT:  71%|███████   | 119/168 [00:26<00:05,  8.92it/s]

Downloading ETHUSDT:  72%|███████▏  | 121/168 [00:26<00:05,  9.36it/s]

Downloading ETHUSDT:  73%|███████▎  | 123/168 [00:26<00:04,  9.23it/s]

Downloading ETHUSDT:  74%|███████▍  | 125/168 [00:27<00:04, 10.22it/s]

Downloading ETHUSDT:  76%|███████▌  | 127/168 [00:27<00:04,  9.37it/s]

Downloading ETHUSDT:  76%|███████▌  | 128/168 [00:27<00:04,  8.62it/s]

Downloading ETHUSDT:  77%|███████▋  | 129/168 [00:27<00:04,  8.41it/s]

Downloading ETHUSDT:  78%|███████▊  | 131/168 [00:27<00:03, 10.54it/s]

Downloading ETHUSDT:  79%|███████▉  | 133/168 [00:28<00:04,  7.33it/s]

Downloading ETHUSDT:  80%|███████▉  | 134/168 [00:28<00:05,  5.99it/s]

Downloading ETHUSDT:  80%|████████  | 135/168 [00:28<00:07,  4.65it/s]

Downloading ETHUSDT:  81%|████████  | 136/168 [00:29<00:09,  3.28it/s]

Downloading ETHUSDT:  82%|████████▏ | 137/168 [00:29<00:09,  3.27it/s]

Downloading ETHUSDT:  82%|████████▏ | 138/168 [00:30<00:08,  3.43it/s]

Downloading ETHUSDT:  83%|████████▎ | 139/168 [00:30<00:08,  3.60it/s]

Downloading ETHUSDT:  83%|████████▎ | 140/168 [00:30<00:07,  3.67it/s]

Downloading ETHUSDT:  84%|████████▍ | 141/168 [00:30<00:07,  3.69it/s]

Downloading ETHUSDT:  85%|████████▍ | 142/168 [00:30<00:06,  4.03it/s]

Downloading ETHUSDT:  85%|████████▌ | 143/168 [00:31<00:05,  4.60it/s]

Downloading ETHUSDT:  86%|████████▋ | 145/168 [00:31<00:03,  6.51it/s]

Downloading ETHUSDT:  87%|████████▋ | 146/168 [00:31<00:03,  6.19it/s]

Downloading ETHUSDT:  88%|████████▊ | 147/168 [00:31<00:03,  5.97it/s]

Downloading ETHUSDT:  88%|████████▊ | 148/168 [00:31<00:03,  5.59it/s]

Downloading ETHUSDT:  89%|████████▊ | 149/168 [00:32<00:03,  5.66it/s]

Downloading ETHUSDT:  89%|████████▉ | 150/168 [00:32<00:02,  6.20it/s]

Downloading ETHUSDT:  90%|█████████ | 152/168 [00:32<00:02,  7.79it/s]

Downloading ETHUSDT:  91%|█████████ | 153/168 [00:32<00:01,  7.53it/s]

Downloading ETHUSDT:  92%|█████████▏| 154/168 [00:32<00:01,  7.13it/s]

Downloading ETHUSDT:  92%|█████████▏| 155/168 [00:32<00:02,  5.91it/s]

Downloading ETHUSDT:  93%|█████████▎| 156/168 [00:33<00:02,  5.00it/s]

Downloading ETHUSDT:  93%|█████████▎| 157/168 [00:33<00:02,  4.69it/s]

Downloading ETHUSDT:  95%|█████████▍| 159/168 [00:33<00:01,  6.37it/s]

Downloading ETHUSDT:  95%|█████████▌| 160/168 [00:33<00:01,  6.08it/s]

Downloading ETHUSDT:  96%|█████████▌| 161/168 [00:33<00:01,  6.41it/s]

Downloading ETHUSDT:  96%|█████████▋| 162/168 [00:34<00:00,  6.32it/s]

Downloading ETHUSDT:  97%|█████████▋| 163/168 [00:34<00:00,  6.05it/s]

Downloading ETHUSDT:  98%|█████████▊| 164/168 [00:34<00:00,  6.32it/s]

Downloading ETHUSDT:  99%|█████████▉| 166/168 [00:34<00:00,  7.71it/s]

Downloading ETHUSDT:  99%|█████████▉| 167/168 [00:34<00:00,  7.14it/s]

Downloading ETHUSDT: 100%|██████████| 168/168 [00:34<00:00,  6.92it/s]

Downloading ETHUSDT: 100%|██████████| 168/168 [00:34<00:00,  4.81it/s]

In [23]:
eth_ts = research.load_ohlc_timeseries(sym, time_interval)
eth_ts

Loading ETHUSDT:   0%|          | 0/168 [00:00<?, ?file/s]

Loading ETHUSDT:   1%|          | 1/168 [00:00<01:21,  2.05file/s]

Loading ETHUSDT:   1%|          | 2/168 [00:00<01:05,  2.54file/s]

Loading ETHUSDT:   2%|▏         | 3/168 [00:01<00:57,  2.88file/s]

Loading ETHUSDT:   3%|▎         | 5/168 [00:01<00:38,  4.21file/s]

Loading ETHUSDT:   4%|▎         | 6/168 [00:01<00:43,  3.72file/s]

Loading ETHUSDT:   4%|▍         | 7/168 [00:02<00:45,  3.55file/s]

Loading ETHUSDT:   5%|▍         | 8/168 [00:02<00:43,  3.66file/s]

Loading ETHUSDT:   5%|▌         | 9/168 [00:02<00:51,  3.12file/s]

Loading ETHUSDT:   6%|▌         | 10/168 [00:03<01:06,  2.37file/s]

Loading ETHUSDT:   7%|▋         | 11/168 [00:04<01:20,  1.95file/s]

Loading ETHUSDT:   7%|▋         | 12/168 [00:04<01:27,  1.79file/s]

Loading ETHUSDT:   8%|▊         | 13/168 [00:05<01:51,  1.39file/s]

Loading ETHUSDT:   8%|▊         | 14/168 [00:06<01:53,  1.35file/s]

Loading ETHUSDT:   9%|▉         | 15/168 [00:07<01:54,  1.33file/s]

Loading ETHUSDT:  10%|▉         | 16/168 [00:09<02:39,  1.05s/file]

Loading ETHUSDT:  10%|█         | 17/168 [00:10<02:46,  1.10s/file]

Loading ETHUSDT:  11%|█         | 18/168 [00:11<02:23,  1.04file/s]

Loading ETHUSDT:  11%|█▏        | 19/168 [00:11<01:56,  1.28file/s]

Loading ETHUSDT:  12%|█▏        | 20/168 [00:11<01:43,  1.43file/s]

Loading ETHUSDT:  12%|█▎        | 21/168 [00:12<01:31,  1.61file/s]

Loading ETHUSDT:  13%|█▎        | 22/168 [00:12<01:28,  1.66file/s]

Loading ETHUSDT:  14%|█▎        | 23/168 [00:13<01:19,  1.81file/s]

Loading ETHUSDT:  14%|█▍        | 24/168 [00:13<01:10,  2.04file/s]

Loading ETHUSDT:  15%|█▍        | 25/168 [00:13<00:57,  2.50file/s]

Loading ETHUSDT:  15%|█▌        | 26/168 [00:14<00:54,  2.60file/s]

Loading ETHUSDT:  16%|█▌        | 27/168 [00:14<00:51,  2.75file/s]

Loading ETHUSDT:  17%|█▋        | 28/168 [00:14<00:49,  2.81file/s]

Loading ETHUSDT:  17%|█▋        | 29/168 [00:15<00:48,  2.88file/s]

Loading ETHUSDT:  18%|█▊        | 30/168 [00:15<00:46,  2.98file/s]

Loading ETHUSDT:  18%|█▊        | 31/168 [00:15<00:44,  3.06file/s]

Loading ETHUSDT:  19%|█▉        | 32/168 [00:15<00:36,  3.77file/s]

Loading ETHUSDT:  20%|█▉        | 33/168 [00:16<00:29,  4.55file/s]

Loading ETHUSDT:  20%|██        | 34/168 [00:16<00:35,  3.74file/s]

Loading ETHUSDT:  21%|██        | 35/168 [00:16<00:39,  3.36file/s]

Loading ETHUSDT:  21%|██▏       | 36/168 [00:17<00:46,  2.82file/s]

Loading ETHUSDT:  22%|██▏       | 37/168 [00:17<00:47,  2.76file/s]

Loading ETHUSDT:  23%|██▎       | 38/168 [00:18<00:47,  2.71file/s]

Loading ETHUSDT:  23%|██▎       | 39/168 [00:18<00:51,  2.52file/s]

Loading ETHUSDT:  24%|██▍       | 40/168 [00:18<00:51,  2.47file/s]

Loading ETHUSDT:  24%|██▍       | 41/168 [00:19<00:57,  2.21file/s]

Loading ETHUSDT:  25%|██▌       | 42/168 [00:20<00:59,  2.13file/s]

Loading ETHUSDT:  26%|██▌       | 43/168 [00:20<01:06,  1.89file/s]

Loading ETHUSDT:  26%|██▌       | 44/168 [00:21<01:02,  1.97file/s]

Loading ETHUSDT:  27%|██▋       | 45/168 [00:21<00:58,  2.11file/s]

Loading ETHUSDT:  27%|██▋       | 46/168 [00:21<00:45,  2.66file/s]

Loading ETHUSDT:  28%|██▊       | 47/168 [00:21<00:41,  2.93file/s]

Loading ETHUSDT:  29%|██▊       | 48/168 [00:22<00:45,  2.63file/s]

Loading ETHUSDT:  29%|██▉       | 49/168 [00:22<00:45,  2.59file/s]

Loading ETHUSDT:  30%|██▉       | 50/168 [00:23<00:43,  2.74file/s]

Loading ETHUSDT:  30%|███       | 51/168 [00:23<00:40,  2.89file/s]

Loading ETHUSDT:  31%|███       | 52/168 [00:23<00:42,  2.70file/s]

Loading ETHUSDT:  32%|███▏      | 53/168 [00:24<00:34,  3.37file/s]

Loading ETHUSDT:  32%|███▏      | 54/168 [00:24<00:30,  3.74file/s]

Loading ETHUSDT:  33%|███▎      | 55/168 [00:24<00:38,  2.94file/s]

Loading ETHUSDT:  33%|███▎      | 56/168 [00:25<00:38,  2.91file/s]

Loading ETHUSDT:  34%|███▍      | 57/168 [00:25<00:39,  2.79file/s]

Loading ETHUSDT:  35%|███▍      | 58/168 [00:25<00:40,  2.71file/s]

Loading ETHUSDT:  35%|███▌      | 59/168 [00:26<00:38,  2.84file/s]

Loading ETHUSDT:  36%|███▌      | 60/168 [00:26<00:30,  3.58file/s]

Loading ETHUSDT:  36%|███▋      | 61/168 [00:26<00:28,  3.70file/s]

Loading ETHUSDT:  37%|███▋      | 62/168 [00:27<00:37,  2.80file/s]

Loading ETHUSDT:  38%|███▊      | 63/168 [00:27<00:36,  2.89file/s]

Loading ETHUSDT:  38%|███▊      | 64/168 [00:27<00:33,  3.10file/s]

Loading ETHUSDT:  39%|███▊      | 65/168 [00:27<00:32,  3.17file/s]

Loading ETHUSDT:  39%|███▉      | 66/168 [00:28<00:31,  3.23file/s]

Loading ETHUSDT:  40%|███▉      | 67/168 [00:28<00:25,  3.91file/s]

Loading ETHUSDT:  40%|████      | 68/168 [00:28<00:22,  4.46file/s]

Loading ETHUSDT:  41%|████      | 69/168 [00:28<00:23,  4.13file/s]

Loading ETHUSDT:  42%|████▏     | 70/168 [00:29<00:27,  3.51file/s]

Loading ETHUSDT:  42%|████▏     | 71/168 [00:29<00:27,  3.47file/s]

Loading ETHUSDT:  43%|████▎     | 72/168 [00:29<00:29,  3.28file/s]

Loading ETHUSDT:  43%|████▎     | 73/168 [00:30<00:24,  3.94file/s]

Loading ETHUSDT:  45%|████▍     | 75/168 [00:30<00:17,  5.43file/s]

Loading ETHUSDT:  45%|████▌     | 76/168 [00:30<00:18,  4.87file/s]

Loading ETHUSDT:  46%|████▌     | 77/168 [00:30<00:23,  3.87file/s]

Loading ETHUSDT:  46%|████▋     | 78/168 [00:31<00:24,  3.73file/s]

Loading ETHUSDT:  47%|████▋     | 79/168 [00:31<00:23,  3.73file/s]

Loading ETHUSDT:  48%|████▊     | 80/168 [00:31<00:22,  3.93file/s]

Loading ETHUSDT:  48%|████▊     | 81/168 [00:31<00:19,  4.37file/s]

Loading ETHUSDT:  49%|████▉     | 82/168 [00:32<00:18,  4.56file/s]

Loading ETHUSDT:  49%|████▉     | 83/168 [00:32<00:22,  3.84file/s]

Loading ETHUSDT:  50%|█████     | 84/168 [00:32<00:23,  3.63file/s]

Loading ETHUSDT:  51%|█████     | 85/168 [00:32<00:22,  3.75file/s]

Loading ETHUSDT:  51%|█████     | 86/168 [00:33<00:22,  3.70file/s]

Loading ETHUSDT:  52%|█████▏    | 87/168 [00:33<00:23,  3.42file/s]

Loading ETHUSDT:  52%|█████▏    | 88/168 [00:33<00:20,  3.97file/s]

Loading ETHUSDT:  53%|█████▎    | 89/168 [00:33<00:19,  4.15file/s]

Loading ETHUSDT:  54%|█████▎    | 90/168 [00:34<00:19,  4.02file/s]

Loading ETHUSDT:  54%|█████▍    | 91/168 [00:34<00:19,  3.93file/s]

Loading ETHUSDT:  55%|█████▍    | 92/168 [00:34<00:20,  3.76file/s]

Loading ETHUSDT:  55%|█████▌    | 93/168 [00:35<00:20,  3.74file/s]

Loading ETHUSDT:  56%|█████▌    | 94/168 [00:35<00:17,  4.18file/s]

Loading ETHUSDT:  57%|█████▋    | 96/168 [00:35<00:11,  6.06file/s]

Loading ETHUSDT:  58%|█████▊    | 97/168 [00:35<00:12,  5.67file/s]

Loading ETHUSDT:  58%|█████▊    | 98/168 [00:35<00:12,  5.82file/s]

Loading ETHUSDT:  59%|█████▉    | 99/168 [00:35<00:13,  5.14file/s]

Loading ETHUSDT:  60%|█████▉    | 100/168 [00:36<00:12,  5.37file/s]

Loading ETHUSDT:  60%|██████    | 101/168 [00:36<00:11,  5.74file/s]

Loading ETHUSDT:  61%|██████▏   | 103/168 [00:36<00:08,  7.53file/s]

Loading ETHUSDT:  62%|██████▏   | 104/168 [00:36<00:11,  5.78file/s]

Loading ETHUSDT:  62%|██████▎   | 105/168 [00:36<00:10,  5.80file/s]

Loading ETHUSDT:  63%|██████▎   | 106/168 [00:37<00:11,  5.40file/s]

Loading ETHUSDT:  64%|██████▎   | 107/168 [00:37<00:11,  5.19file/s]

Loading ETHUSDT:  64%|██████▍   | 108/168 [00:37<00:11,  5.42file/s]

Loading ETHUSDT:  65%|██████▌   | 110/168 [00:37<00:08,  6.58file/s]

Loading ETHUSDT:  66%|██████▌   | 111/168 [00:37<00:08,  6.53file/s]

Loading ETHUSDT:  67%|██████▋   | 112/168 [00:38<00:08,  6.39file/s]

Loading ETHUSDT:  67%|██████▋   | 113/168 [00:38<00:08,  6.31file/s]

Loading ETHUSDT:  68%|██████▊   | 114/168 [00:38<00:09,  5.94file/s]

Loading ETHUSDT:  68%|██████▊   | 115/168 [00:38<00:09,  5.72file/s]

Loading ETHUSDT:  69%|██████▉   | 116/168 [00:38<00:08,  6.38file/s]

Loading ETHUSDT:  70%|██████▉   | 117/168 [00:38<00:07,  6.91file/s]

Loading ETHUSDT:  70%|███████   | 118/168 [00:39<00:08,  5.70file/s]

Loading ETHUSDT:  71%|███████   | 119/168 [00:39<00:08,  5.88file/s]

Loading ETHUSDT:  71%|███████▏  | 120/168 [00:39<00:07,  6.24file/s]

Loading ETHUSDT:  72%|███████▏  | 121/168 [00:39<00:07,  6.37file/s]

Loading ETHUSDT:  73%|███████▎  | 122/168 [00:39<00:07,  6.48file/s]

Loading ETHUSDT:  73%|███████▎  | 123/168 [00:39<00:07,  6.10file/s]

Loading ETHUSDT:  74%|███████▍  | 124/168 [00:40<00:06,  6.63file/s]

Loading ETHUSDT:  74%|███████▍  | 125/168 [00:40<00:05,  7.24file/s]

Loading ETHUSDT:  75%|███████▌  | 126/168 [00:40<00:06,  6.50file/s]

Loading ETHUSDT:  76%|███████▌  | 127/168 [00:40<00:06,  6.17file/s]

Loading ETHUSDT:  76%|███████▌  | 128/168 [00:40<00:07,  5.49file/s]

Loading ETHUSDT:  77%|███████▋  | 129/168 [00:40<00:07,  5.51file/s]

Loading ETHUSDT:  78%|███████▊  | 131/168 [00:41<00:04,  7.54file/s]

Loading ETHUSDT:  79%|███████▊  | 132/168 [00:41<00:05,  6.43file/s]

Loading ETHUSDT:  79%|███████▉  | 133/168 [00:41<00:07,  4.38file/s]

Loading ETHUSDT:  80%|███████▉  | 134/168 [00:42<00:09,  3.52file/s]

Loading ETHUSDT:  80%|████████  | 135/168 [00:42<00:12,  2.63file/s]

Loading ETHUSDT:  81%|████████  | 136/168 [00:43<00:17,  1.87file/s]

Loading ETHUSDT:  82%|████████▏ | 137/168 [00:44<00:15,  1.96file/s]

Loading ETHUSDT:  82%|████████▏ | 138/168 [00:44<00:14,  2.12file/s]

Loading ETHUSDT:  83%|████████▎ | 139/168 [00:44<00:13,  2.23file/s]

Loading ETHUSDT:  83%|████████▎ | 140/168 [00:45<00:11,  2.37file/s]

Loading ETHUSDT:  84%|████████▍ | 141/168 [00:45<00:11,  2.43file/s]

Loading ETHUSDT:  85%|████████▍ | 142/168 [00:45<00:09,  2.68file/s]

Loading ETHUSDT:  85%|████████▌ | 143/168 [00:46<00:08,  3.06file/s]

Loading ETHUSDT:  86%|████████▋ | 145/168 [00:46<00:05,  4.42file/s]

Loading ETHUSDT:  87%|████████▋ | 146/168 [00:46<00:05,  4.19file/s]

Loading ETHUSDT:  88%|████████▊ | 147/168 [00:46<00:05,  4.08file/s]

Loading ETHUSDT:  88%|████████▊ | 148/168 [00:47<00:05,  3.74file/s]

Loading ETHUSDT:  89%|████████▊ | 149/168 [00:47<00:05,  3.73file/s]

Loading ETHUSDT:  89%|████████▉ | 150/168 [00:47<00:04,  4.18file/s]

Loading ETHUSDT:  90%|████████▉ | 151/168 [00:47<00:03,  4.78file/s]

Loading ETHUSDT:  90%|█████████ | 152/168 [00:47<00:02,  5.52file/s]

Loading ETHUSDT:  91%|█████████ | 153/168 [00:48<00:02,  5.19file/s]

Loading ETHUSDT:  92%|█████████▏| 154/168 [00:48<00:02,  4.92file/s]

Loading ETHUSDT:  92%|█████████▏| 155/168 [00:48<00:03,  4.10file/s]

Loading ETHUSDT:  93%|█████████▎| 156/168 [00:49<00:03,  3.55file/s]

Loading ETHUSDT:  93%|█████████▎| 157/168 [00:49<00:03,  3.16file/s]

Loading ETHUSDT:  94%|█████████▍| 158/168 [00:49<00:02,  3.91file/s]

Loading ETHUSDT:  95%|█████████▍| 159/168 [00:49<00:01,  4.57file/s]

Loading ETHUSDT:  95%|█████████▌| 160/168 [00:50<00:01,  4.20file/s]

Loading ETHUSDT:  96%|█████████▌| 161/168 [00:50<00:01,  4.49file/s]

Loading ETHUSDT:  96%|█████████▋| 162/168 [00:50<00:01,  4.35file/s]

Loading ETHUSDT:  97%|█████████▋| 163/168 [00:50<00:01,  4.10file/s]

Loading ETHUSDT:  98%|█████████▊| 164/168 [00:50<00:00,  4.36file/s]

Loading ETHUSDT:  98%|█████████▊| 165/168 [00:51<00:00,  4.93file/s]

Loading ETHUSDT:  99%|█████████▉| 166/168 [00:51<00:00,  5.50file/s]

Loading ETHUSDT:  99%|█████████▉| 167/168 [00:51<00:00,  4.88file/s]

Loading ETHUSDT: 100%|██████████| 168/168 [00:51<00:00,  4.63file/s]

Loading ETHUSDT: 100%|██████████| 168/168 [00:51<00:00,  3.25file/s]

shape: (4_032, 5)
┌─────────────────────┬─────────┬─────────┬─────────┬─────────┐
│ datetime            ┆ open    ┆ high    ┆ low     ┆ close   │
│ ---                 ┆ ---     ┆ ---     ┆ ---     ┆ ---     │
│ datetime[μs]        ┆ f64     ┆ f64     ┆ f64     ┆ f64     │
╞═════════════════════╪═════════╪═════════╪═════════╪═════════╡
│ 2026-01-21 00:00:00 ┆ 2938.25 ┆ 2968.0  ┆ 2920.08 ┆ 2958.32 │
│ 2026-01-21 01:00:00 ┆ 2958.31 ┆ 2973.06 ┆ 2953.62 ┆ 2963.66 │
│ 2026-01-21 02:00:00 ┆ 2963.66 ┆ 2973.75 ┆ 2956.22 ┆ 2960.65 │
│ 2026-01-21 03:00:00 ┆ 2960.65 ┆ 2983.7  ┆ 2959.79 ┆ 2980.27 │
│ 2026-01-21 04:00:00 ┆ 2980.26 ┆ 2984.45 ┆ 2973.26 ┆ 2977.83 │
│ …                   ┆ …       ┆ …       ┆ …       ┆ …       │
│ 2026-07-07 19:00:00 ┆ 1785.59 ┆ 1791.48 ┆ 1771.02 ┆ 1789.59 │
│ 2026-07-07 20:00:00 ┆ 1789.59 ┆ 1792.27 ┆ 1780.43 ┆ 1783.32 │
│ 2026-07-07 21:00:00 ┆ 1783.31 ┆ 1788.61 ┆ 1770.0  ┆ 1772.84 │
│ 2026-07-07 22:00:00 ┆ 1772.85 ┆ 1777.9  ┆ 1764.5  ┆ 1774.42 │
│ 2026-07-07 23:00:00 ┆ 1774.42 ┆ 1780.39 ┆ 1767.49 ┆ 1770.67 │
└─────────────────────┴─────────┴─────────┴─────────┴─────────┘

In [24]:
research.plot_static_timeseries(eth_ts, sym, 'close', time_interval)

## Feature Engineering

In [25]:
eth_ts = research.add_log_return_features(eth_ts, 'close', forecast_horizon, max_no_lags=max_lags)
eth_ts = eth_ts.drop_nulls()
eth_ts

shape: (4_027, 10)
┌─────────────────────┬─────────┬─────────┬─────────┬─────────┬──────────────────┬────────────────────────┬────────────────────────┬────────────────────────┬────────────────────────┐
│ datetime            ┆ open    ┆ high    ┆ low     ┆ close   ┆ close_log_return ┆ close_log_return_lag_1 ┆ close_log_return_lag_2 ┆ close_log_return_lag_3 ┆ close_log_return_lag_4 │
│ ---                 ┆ ---     ┆ ---     ┆ ---     ┆ ---     ┆ ---              ┆ ---                    ┆ ---                    ┆ ---                    ┆ ---                    │
│ datetime[μs]        ┆ f64     ┆ f64     ┆ f64     ┆ f64     ┆ f64              ┆ f64                    ┆ f64                    ┆ f64                    ┆ f64                    │
╞═════════════════════╪═════════╪═════════╪═════════╪═════════╪══════════════════╪════════════════════════╪════════════════════════╪════════════════════════╪════════════════════════╡
│ 2026-01-21 05:00:00 ┆ 2977.84 ┆ 3001.01 ┆ 2976.34 ┆ 2991.71 ┆ 0.00465          ┆ -0.000819              ┆ 0.006605               ┆ -0.001016              ┆ 0.001803               │
│ 2026-01-21 06:00:00 ┆ 2991.71 ┆ 2992.5  ┆ 2973.76 ┆ 2979.01 ┆ -0.004254        ┆ 0.00465                ┆ -0.000819              ┆ 0.006605               ┆ -0.001016              │
│ 2026-01-21 07:00:00 ┆ 2979.01 ┆ 2984.42 ┆ 2964.45 ┆ 2969.01 ┆ -0.003362        ┆ -0.004254              ┆ 0.00465                ┆ -0.000819              ┆ 0.006605               │
│ 2026-01-21 08:00:00 ┆ 2969.02 ┆ 2973.18 ┆ 2954.15 ┆ 2964.0  ┆ -0.001689        ┆ -0.003362              ┆ -0.004254              ┆ 0.00465                ┆ -0.000819              │
│ 2026-01-21 09:00:00 ┆ 2963.99 ┆ 2973.62 ┆ 2947.0  ┆ 2952.46 ┆ -0.003901        ┆ -0.001689              ┆ -0.003362              ┆ -0.004254              ┆ 0.00465                │
│ …                   ┆ …       ┆ …       ┆ …       ┆ …       ┆ …                ┆ …                      ┆ …                      ┆ …                      ┆ …                      │
│ 2026-07-07 19:00:00 ┆ 1785.59 ┆ 1791.48 ┆ 1771.02 ┆ 1789.59 ┆ 0.002232         ┆ -0.01339               ┆ 0.004575               ┆ 0.00264                ┆ 0.004407               │
│ 2026-07-07 20:00:00 ┆ 1789.59 ┆ 1792.27 ┆ 1780.43 ┆ 1783.32 ┆ -0.00351         ┆ 0.002232               ┆ -0.01339               ┆ 0.004575               ┆ 0.00264                │
│ 2026-07-07 21:00:00 ┆ 1783.31 ┆ 1788.61 ┆ 1770.0  ┆ 1772.84 ┆ -0.005894        ┆ -0.00351               ┆ 0.002232               ┆ -0.01339               ┆ 0.004575               │
│ 2026-07-07 22:00:00 ┆ 1772.85 ┆ 1777.9  ┆ 1764.5  ┆ 1774.42 ┆ 0.000891         ┆ -0.005894              ┆ -0.00351               ┆ 0.002232               ┆ -0.01339               │
│ 2026-07-07 23:00:00 ┆ 1774.42 ┆ 1780.39 ┆ 1767.49 ┆ 1770.67 ┆ -0.002116        ┆ 0.000891               ┆ -0.005894              ┆ -0.00351               ┆ 0.002232               │
└─────────────────────┴─────────┴─────────┴─────────┴─────────┴──────────────────┴────────────────────────┴────────────────────────┴────────────────────────┴────────────────────────┘

In [26]:
research.plot_distribution(eth_ts, target, no_bins=100)

alt.Chart(...)

In [27]:
research.auto_reg_corr_matrx(eth_ts, target, max_lags)

shape: (5, 5)
┌──────────────────┬────────────────────────┬────────────────────────┬────────────────────────┬────────────────────────┐
│ close_log_return ┆ close_log_return_lag_1 ┆ close_log_return_lag_2 ┆ close_log_return_lag_3 ┆ close_log_return_lag_4 │
│ ---              ┆ ---                    ┆ ---                    ┆ ---                    ┆ ---                    │
│ f64              ┆ f64                    ┆ f64                    ┆ f64                    ┆ f64                    │
╞══════════════════╪════════════════════════╪════════════════════════╪════════════════════════╪════════════════════════╡
│ 1.0              ┆ 0.000453               ┆ -0.008837              ┆ -0.001778              ┆ -0.005543              │
│ 0.000453         ┆ 1.0                    ┆ 0.000439               ┆ -0.008896              ┆ -0.001822              │
│ -0.008837        ┆ 0.000439               ┆ 1.0                    ┆ 0.000438               ┆ -0.008806              │
│ -0.001778        ┆ -0.008896              ┆ 0.000438               ┆ 1.0                    ┆ 0.000323               │
│ -0.005543        ┆ -0.001822              ┆ -0.008806              ┆ 0.000323               ┆ 1.0                    │
└──────────────────┴────────────────────────┴────────────────────────┴────────────────────────┴────────────────────────┘

## Benchmark Linear Models

In [28]:
eth_benchmark = research.benchmark_linear_models(
    eth_ts, target, feature_pool, annualized_rate, max_no_features=3, loss=nn.L1Loss()
)
eth_benchmark

shape: (14, 18)
┌───────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ features  ┆ target   ┆ no_trade ┆ win_rate ┆ avg_win  ┆ avg_loss ┆ best_tra ┆ worst_tr ┆ ev       ┆ std      ┆ total_lo ┆ compound ┆ max_draw ┆ equity_t ┆ equity_p ┆ sharpe   ┆ weights  ┆ biases   │
│ ---       ┆ ---      ┆ s        ┆ ---      ┆ ---      ┆ ---      ┆ de       ┆ ade      ┆ ---      ┆ ---      ┆ g_return ┆ _return  ┆ down     ┆ rough    ┆ eak      ┆ ---      ┆ ---      ┆ ---      │
│ str       ┆ str      ┆ ---      ┆ f64      ┆ f64      ┆ f64      ┆ ---      ┆ ---      ┆ f64      ┆ f64      ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ f64      ┆ str      ┆ str      │
│           ┆          ┆ i64      ┆          ┆          ┆          ┆ f64      ┆ f64      ┆          ┆          ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆          ┆          ┆          │
╞═══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╡
│ close_log ┆ close_lo ┆ 1007     ┆ 0.536246 ┆ 0.004448 ┆ -0.00425 ┆ 0.061749 ┆ -0.02960 ┆ 0.000414 ┆ 0.006799 ┆ 0.416791 ┆ 1.517086 ┆ -0.15424 ┆ -0.05291 ┆ 0.512664 ┆ 5.69728  ┆ [-0.0103 ┆ -6.26047 │
│ _return_l ┆ g_return ┆          ┆          ┆          ┆ 1        ┆          ┆ 9        ┆          ┆          ┆          ┆          ┆ 3        ┆ 9        ┆          ┆          ┆ 1838 -0. ┆ 76758234 │
│ ag_1,clos ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ 01492931 ┆ 95e-05   │
│ e_log_ret ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ ]        ┆          │
│ urn_lag_4 ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
│ close_log ┆ close_lo ┆ 1007     ┆ 0.512413 ┆ 0.004429 ┆ -0.00428 ┆ 0.061749 ┆ -0.03813 ┆ 0.000182 ┆ 0.00681  ┆ 0.183743 ┆ 1.201706 ┆ -0.17578 ┆ -0.00080 ┆ 0.3334   ┆ 2.507905 ┆ [-0.0075 ┆ -7.13812 │
│ _return_l ┆ g_return ┆          ┆          ┆          ┆          ┆          ┆ 6        ┆          ┆          ┆          ┆          ┆          ┆ 6        ┆          ┆          ┆ 405]     ┆ 40559276 │
│ ag_4      ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ 2e-05    │
│ close_log ┆ close_lo ┆ 1007     ┆ 0.532274 ┆ 0.004261 ┆ -0.00446 ┆ 0.038136 ┆ -0.06174 ┆ 0.000179 ┆ 0.00681  ┆ 0.18066  ┆ 1.198008 ┆ -0.14910 ┆ 0.003219 ┆ 0.293561 ┆ 2.465799 ┆ [-0.0282 ┆ -7.48074 │
│ _return_l ┆ g_return ┆          ┆          ┆          ┆ 5        ┆          ┆ 9        ┆          ┆          ┆          ┆          ┆ 8        ┆          ┆          ┆          ┆ 4356 -0. ┆ 88999795 │
│ ag_1,clos ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ 01870682 ┆ 17e-05   │
│ e_log_ret ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ ]        ┆          │
│ urn_lag_3 ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
│ close_log ┆ close_lo ┆ 1007     ┆ 0.525323 ┆ 0.004291 ┆ -0.00442 ┆ 0.038136 ┆ -0.06174 ┆ 0.000152 ┆ 0.00681  ┆ 0.15305  ┆ 1.165383 ┆ -0.14624 ┆ -0.00219 ┆ 0.269912 ┆ 2.088748 ┆ [-0.0207 ┆ -7.41055 │
│ _return_l ┆ g_return ┆          ┆          ┆          ┆ 9        ┆          ┆ 9        ┆          ┆          ┆          ┆          ┆ 1        ┆ 1        ┆          ┆          ┆ 7781 -0. ┆ 84644712 │
│ ag_1,clos ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ 02156897 ┆ 51e-05   │
│ e_log_ret ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ -0.00667 ┆          │
│ urn_lag_3 ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ 758]     ┆          │
│ ,close_lo ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
│ g_return_ ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
│ lag_4     ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
│ close_log ┆ close_lo ┆ 1007     ┆ 0.513406 ┆ 0.004368 ┆ -0.00434 ┆ 0.033773 ┆ -0.06174 ┆ 0.000129 ┆ 0.006811 ┆ 0.129716 ┆ 1.138505 ┆ -0.15321 ┆ 0.003382 ┆ 0.243429 ┆ 1.770176 ┆ [-0.0229 ┆ -5.30120 │
│ _return_l ┆ g_return ┆          ┆          ┆          ┆ 4        ┆          ┆ 9        ┆          ┆          ┆          ┆          ┆ 4        ┆          ┆          ┆          ┆ 476  -0. ┆ 45100331 │
│ ag_3,clos ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ 00231006 ┆ 306e-05  │
│ e_log_ret ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ ]        ┆          │
│ urn_lag_4 ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
│ …         ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        ┆ …        │
│ close_log ┆ close_lo ┆ 1007     ┆ 0.522344 ┆ 0.004148 ┆ -0.00458 ┆ 0.038136 ┆ -0.06174 ┆ -0.00002 ┆ 0.006812 ┆ -0.02333 ┆ 0.976936 ┆ -0.32546 ┆ -0.04990 ┆ 0.275558 ┆ -0.31836 ┆ [-0.0225 ┆ -6.24342 │
│ _return_l ┆ g_return ┆          ┆          ┆          ┆ 5        ┆          ┆ 9        ┆ 3        ┆          ┆ 4        ┆          ┆ 5        ┆ 8        ┆          ┆ 9        ┆ 6055 -0. ┆ 35587716 │
│ ag_1,clos ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ 03566389 ┆ 1e-05    │
│ e_log_ret ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ -0.01544 ┆          │
│ urn_lag_2 ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ 781]     ┆          │
│ ,close_lo ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
│ g_return_ ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
│ lag_3     ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
│ close_log ┆ close_lo ┆ 1007     ┆ 0.505462 ┆ 0.004184 ┆ -0.00453 ┆ 0.038136 ┆ -0.06174 ┆ -0.00012 ┆ 0.006811 ┆ -0.12744 ┆ 0.880339 ┆ -0.3061  ┆ -0.15259 ┆ 0.153504 ┆ -1.73922 ┆ [-0.0271 ┆ -5.00467 │
│ _return_l ┆ g_return ┆          ┆          ┆          ┆ 3        ┆          ┆ 9        ┆ 7        ┆          ┆ 9        ┆          ┆          ┆ 7        ┆          ┆ 4        ┆ 7156 -0. ┆ 54040522 │
│ ag_2,clos ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ 01728193 ┆ 5e-05    │
│ e_log_ret ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ ]        ┆          │
│ urn_lag_3 ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
│ close_log ┆ close_lo ┆ 1007     ┆ 0.503476 ┆ 0.004157 ┆ -0.00455 ┆ 0.038136 ┆ -0.06174 ┆ -0.00017 ┆ 0.00681  ┆ -0.17238 ┆ 0.841655 ┆ -0.39092 ┆ -0.20597 ┆ 0.18495  ┆ -2.35278 ┆ [-0.0315 ┆ -5.58279 │
│ _return_l ┆ g_return ┆          ┆          ┆          ┆ 9        ┆          ┆ 9        ┆ 1        ┆          ┆ 5        ┆          ┆ 9        ┆ 9        ┆          ┆ 6        ┆ 7542 -0. ┆ 71664257 │
│ ag_2,clos ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ 01495309 ┆ 35e-05   │
│ e_log_ret ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ -0.00155 ┆          │
│ urn_lag_3 ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ 121]     ┆          │
│ ,close_lo ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
│ g_return_ ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
│ lag_4     ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
│ close_log ┆ close_lo ┆ 1007     ┆ 0.489573 ┆ 0.004195 ┆ -0.00451 ┆ 0.038136 ┆ -0.06174 ┆ -0.00024 ┆ 0.006807 ┆ -0.25067 ┆ 0.778274 ┆ -0.53617 ┆ -0.27586 ┆ 0.260307 ┆ -3.42254 ┆ [-0.0345 ┆ -5.98889 │
│ _return_l ┆ g_return ┆          ┆          ┆          ┆ 1        ┆          ┆ 9        ┆ 9        ┆          ┆ 7        ┆          ┆ 3        ┆ 6        ┆          ┆ 9        ┆ 8383]    ┆ 78285016 │
│ ag_2      ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ 49e-05   │
│ close_log ┆ close_lo ┆ 1007     ┆ 0.487587 ┆ 0.00421  ┆ -0.00449 ┆ 0.038136 ┆ -0.06174 ┆ -0.00025 ┆ 0.006807 ┆ -0.25318 ┆ 0.776324 ┆ -0.53103 ┆ -0.27837 ┆ 0.252658 ┆ -3.45685 ┆ [-0.0344 ┆ -6.13560 │
│ _return_l ┆ g_return ┆          ┆          ┆          ┆ 6        ┆          ┆ 9        ┆ 1        ┆          ┆ 6        ┆          ┆ 3        ┆ 5        ┆          ┆ 4        ┆ 2086     ┆ 40532700 │
│ ag_2,clos ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ 0.001642 ┆ 72e-05   │
│ e_log_ret ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ 66]      ┆          │
│ urn_lag_4 ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          │
└───────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┘

In [29]:
eth_best = eth_benchmark.row(0, named=True)
eth_best_features = eth_best['features'].split(',')
eth_best_features

['close_log_return_lag_1', 'close_log_return_lag_4']

## Best Model: Trade-Level Performance

In [30]:
eth_model = models.LinearModel(len(eth_best_features))
eth_model_trades = research.learn_model_trades(eth_ts, eth_best_features, target, eth_model, loss=nn.L1Loss())
research.plot_column(eth_model_trades, 'equity_curve')

alt.Chart(...)

## Add Transaction Fees

In [31]:
eth_model_trades = research.add_tx_fees_log(eth_model_trades, maker_fee, taker_fee)
research.plot_column(eth_model_trades, 'equity_curve_net_taker')

alt.Chart(...)

## Save Model

In [32]:
torch.save(eth_model.state_dict(), 'ETHUSDT_model_weights.pth')
print(f"Saved ETHUSDT model with features {eth_best_features}")

Saved ETHUSDT model with features ['close_log_return_lag_1', 'close_log_return_lag_4']

## Out-of-Sample Validation (Walk-Forward)

Same walk-forward validation as BTCUSDT: pick features and train fresh on each fold's training window only, evaluate once on that fold's unseen test window, then compare the stitched OOS result against buy-and-hold and a random-signal null distribution.

In [33]:
eth_wf_folds, eth_oos_y_test, eth_oos_y_hat = research.walk_forward_eval(
    eth_ts, target, feature_pool, annualized_rate, n_folds=5, loss=nn.L1Loss()
)
eth_wf_folds

shape: (5, 18)
┌───────────┬───────────┬───────────┬──────────┬──────────┬───────────┬───────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────┬──────────┐
│ features  ┆ target    ┆ no_trades ┆ win_rate ┆ avg_win  ┆ avg_loss  ┆ best_trad ┆ worst_tr ┆ ev       ┆ std      ┆ total_lo ┆ compound ┆ max_draw ┆ equity_t ┆ equity_p ┆ sharpe   ┆ fold ┆ no_test_ │
│ ---       ┆ ---       ┆ ---       ┆ ---      ┆ ---      ┆ ---       ┆ e         ┆ ade      ┆ ---      ┆ ---      ┆ g_return ┆ _return  ┆ down     ┆ rough    ┆ eak      ┆ ---      ┆ ---  ┆ obs      │
│ str       ┆ str       ┆ i64       ┆ f64      ┆ f64      ┆ f64       ┆ ---       ┆ ---      ┆ f64      ┆ f64      ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ ---      ┆ f64      ┆ i64  ┆ ---      │
│           ┆           ┆           ┆          ┆          ┆           ┆ f64       ┆ f64      ┆          ┆          ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆ f64      ┆          ┆      ┆ i64      │
╞═══════════╪═══════════╪═══════════╪══════════╪══════════╪═══════════╪═══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════╪══════════╡
│ close_log ┆ close_log ┆ 402       ┆ 0.445274 ┆ 0.003262 ┆ -0.002947 ┆ 0.025672  ┆ -0.02710 ┆ -0.00018 ┆ 0.004544 ┆ -0.07342 ┆ 0.929202 ┆ -0.15353 ┆ -0.09991 ┆ 0.053617 ┆ -3.76240 ┆ 0    ┆ 402      │
│ _return_l ┆ _return   ┆           ┆          ┆          ┆           ┆           ┆ 6        ┆ 3        ┆          ┆ 9        ┆          ┆          ┆ 4        ┆          ┆ 6        ┆      ┆          │
│ ag_2,clos ┆           ┆           ┆          ┆          ┆           ┆           ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆      ┆          │
│ e_log_ret ┆           ┆           ┆          ┆          ┆           ┆           ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆      ┆          │
│ urn_lag_4 ┆           ┆           ┆          ┆          ┆           ┆           ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆      ┆          │
│ close_log ┆ close_log ┆ 402       ┆ 0.504975 ┆ 0.00288  ┆ -0.002565 ┆ 0.022635  ┆ -0.01842 ┆ 0.000185 ┆ 0.004134 ┆ 0.074211 ┆ 1.077034 ┆ -0.05568 ┆ -0.04696 ┆ 0.08202  ┆ 4.179004 ┆ 1    ┆ 402      │
│ _return_l ┆ _return   ┆           ┆          ┆          ┆           ┆           ┆ 9        ┆          ┆          ┆          ┆          ┆ 5        ┆ 2        ┆          ┆          ┆      ┆          │
│ ag_3,clos ┆           ┆           ┆          ┆          ┆           ┆           ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆      ┆          │
│ e_log_ret ┆           ┆           ┆          ┆          ┆           ┆           ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆      ┆          │
│ urn_lag_4 ┆           ┆           ┆          ┆          ┆           ┆           ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆      ┆          │
│ close_log ┆ close_log ┆ 402       ┆ 0.512438 ┆ 0.003713 ┆ -0.003431 ┆ 0.038136  ┆ -0.03272 ┆ 0.00023  ┆ 0.005682 ┆ 0.092381 ┆ 1.096783 ┆ -0.07137 ┆ -0.06166 ┆ 0.099578 ┆ 3.785588 ┆ 2    ┆ 402      │
│ _return_l ┆ _return   ┆           ┆          ┆          ┆           ┆           ┆ 6        ┆          ┆          ┆          ┆          ┆          ┆ 1        ┆          ┆          ┆      ┆          │
│ ag_2      ┆           ┆           ┆          ┆          ┆           ┆           ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆      ┆          │
│ close_log ┆ close_log ┆ 402       ┆ 0.5199   ┆ 0.004505 ┆ -0.005103 ┆ 0.035194  ┆ -0.02960 ┆ -0.00010 ┆ 0.007238 ┆ -0.04330 ┆ 0.957618 ┆ -0.19872 ┆ -0.09601 ┆ 0.102706 ┆ -1.39304 ┆ 3    ┆ 402      │
│ _return_l ┆ _return   ┆           ┆          ┆          ┆           ┆           ┆ 9        ┆ 8        ┆          ┆ 7        ┆          ┆ 5        ┆ 9        ┆          ┆ 8        ┆      ┆          │
│ ag_1,clos ┆           ┆           ┆          ┆          ┆           ┆           ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆      ┆          │
│ e_log_ret ┆           ┆           ┆          ┆          ┆           ┆           ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆      ┆          │
│ urn_lag_3 ┆           ┆           ┆          ┆          ┆           ┆           ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆      ┆          │
│ close_log ┆ close_log ┆ 406       ┆ 0.522167 ┆ 0.003824 ┆ -0.004441 ┆ 0.021677  ┆ -0.06174 ┆ -0.00012 ┆ 0.006633 ┆ -0.05073 ┆ 0.950529 ┆ -0.12323 ┆ -0.10554 ┆ 0.017688 ┆ -1.76323 ┆ 4    ┆ 406      │
│ _return_l ┆ _return   ┆           ┆          ┆          ┆           ┆           ┆ 9        ┆ 5        ┆          ┆ 6        ┆          ┆          ┆ 2        ┆          ┆          ┆      ┆          │
│ ag_1,clos ┆           ┆           ┆          ┆          ┆           ┆           ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆      ┆          │
│ e_log_ret ┆           ┆           ┆          ┆          ┆           ┆           ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆      ┆          │
│ urn_lag_3 ┆           ┆           ┆          ┆          ┆           ┆           ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆      ┆          │
└───────────┴───────────┴───────────┴──────────┴──────────┴───────────┴───────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────┴──────────┘

In [34]:
eth_oos_perf = research.eval_model_performance(eth_oos_y_test, eth_oos_y_hat, feature_pool, target, annualized_rate)
eth_oos_perf

{'features': 'close_log_return_lag_1,close_log_return_lag_2,close_log_return_lag_3,close_log_return_lag_4',
 'target': 'close_log_return',
 'no_trades': 2014,
 'win_rate': 0.5009930486593843,
 'avg_win': 0.003652703265253734,
 'avg_loss': -0.0036681168901723776,
 'best_trade': 0.03813611716032028,
 'worst_trade': -0.06174878776073456,
 'ev': -4.368818183821295e-07,
 'std': 0.00576775660738349,
 'total_log_return': -0.0008798742201179266,
 'compound_return': np.float64(0.9991205127556987),
 'max_drawdown': -0.2515544891357422,
 'equity_trough': -0.12039056420326233,
 'equity_peak': 0.19586893916130066,
 'sharpe': np.float64(-0.0070893937631250695)}

### Baselines: Buy & Hold and a Random-Signal Null Distribution

In [35]:
eth_bh_perf = research.buy_and_hold_performance(eth_oos_y_test, annualized_rate)
eth_bh_perf

{'strategy': 'buy_and_hold',
 'no_periods': 2014,
 'total_log_return': -0.276516854763031,
 'compound_return': 0.7584208250045776,
 'std': 0.005764689762145281,
 'max_drawdown': -0.476358562707901,
 'sharpe': -2.2291447850727555}

In [36]:
eth_null_sharpes = research.random_signal_sharpes(eth_oos_y_test, annualized_rate, n_trials=1000, seed=42)
eth_p_value = research.sharpe_p_value(eth_oos_perf['sharpe'], eth_null_sharpes)

print(f"ETHUSDT OOS model Sharpe:      {eth_oos_perf['sharpe']:.2f}")
print(f"ETHUSDT Buy & Hold Sharpe:     {eth_bh_perf['sharpe']:.2f}")
print(f"Random-signal null Sharpe:     mean={eth_null_sharpes.mean():.2f}, std={eth_null_sharpes.std():.2f}")
print(f"P(random signal Sharpe >= model OOS Sharpe): {eth_p_value:.3f}")

ETHUSDT OOS model Sharpe:      -0.01
ETHUSDT Buy & Hold Sharpe:     -2.23
Random-signal null Sharpe:     mean=-0.00, std=2.05
P(random signal Sharpe >= model OOS Sharpe): 0.489

In [37]:
eth_oos_trades = research.model_trade_results(eth_oos_y_test, eth_oos_y_hat)
eth_bh_equity_curve = np.cumsum(eth_oos_y_test.numpy().flatten())

plt.figure(figsize=(12, 6))
plt.plot(eth_oos_trades['equity_curve'], label='Model (walk-forward OOS)')
plt.plot(eth_bh_equity_curve, label='Buy & Hold')
plt.title('ETHUSDT: Out-of-Sample Equity Curve vs Buy & Hold')
plt.xlabel('Period (stitched across folds)')
plt.ylabel('Cumulative Log Return')
plt.legend()
plt.tight_layout()
plt.show()

/var/folders/69/1t3g51kj5y96vspv1zh9f1x40000gn/T/ipykernel_30504/3009361041.py:12: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

# Part 3: BTCUSDT vs ETHUSDT Comparison

In [38]:
comparison = pl.concat([
    btc_benchmark.head(1).with_columns(pl.lit('BTCUSDT').alias('sym')),
    eth_benchmark.head(1).with_columns(pl.lit('ETHUSDT').alias('sym')),
]).select(['sym'] + [c for c in btc_benchmark.columns if c != 'sym'])
comparison

shape: (2, 19)
┌─────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┐
│ sym     ┆ features ┆ target   ┆ no_trade ┆ win_rate ┆ avg_win  ┆ avg_loss ┆ best_tra ┆ worst_tr ┆ ev       ┆ std     ┆ total_l ┆ compoun ┆ max_dra ┆ equity_ ┆ equity_ ┆ sharpe  ┆ weights ┆ biases  │
│ ---     ┆ ---      ┆ ---      ┆ s        ┆ ---      ┆ ---      ┆ ---      ┆ de       ┆ ade      ┆ ---      ┆ ---     ┆ og_retu ┆ d_retur ┆ wdown   ┆ trough  ┆ peak    ┆ ---     ┆ ---     ┆ ---     │
│ str     ┆ str      ┆ str      ┆ ---      ┆ f64      ┆ f64      ┆ f64      ┆ ---      ┆ ---      ┆ f64      ┆ f64     ┆ rn      ┆ n       ┆ ---     ┆ ---     ┆ ---     ┆ f64     ┆ str     ┆ str     │
│         ┆          ┆          ┆ i64      ┆          ┆          ┆          ┆ f64      ┆ f64      ┆          ┆         ┆ ---     ┆ ---     ┆ f64     ┆ f64     ┆ f64     ┆         ┆         ┆         │
│         ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆         ┆ f64     ┆ f64     ┆         ┆         ┆         ┆         ┆         ┆         │
╞═════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╪═════════╡
│ BTCUSDT ┆ close_lo ┆ close_lo ┆ 1013     ┆ 0.530109 ┆ 0.003668 ┆ -0.00321 ┆ 0.049699 ┆ -0.02293 ┆ 0.000434 ┆ 0.00525 ┆ 0.43993 ┆ 1.55261 ┆ -0.0875 ┆ -0.0536 ┆ 0.44276 ┆ 7.73160 ┆ [-0.046 ┆ -1.1558 │
│         ┆ g_return ┆ g_return ┆          ┆          ┆          ┆ 4        ┆          ┆ 6        ┆          ┆ 7       ┆ 9       ┆ 3       ┆ 31      ┆ 1       ┆ 9       ┆ 3       ┆ 38382   ┆ 8482003 │
│         ┆ _lag_2,c ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ -0.0281 ┆ 65901e- │
│         ┆ lose_log ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ 6361]   ┆ 05      │
│         ┆ _return_ ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│         ┆ lag_4    ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│ ETHUSDT ┆ close_lo ┆ close_lo ┆ 1007     ┆ 0.536246 ┆ 0.004448 ┆ -0.00425 ┆ 0.061749 ┆ -0.02960 ┆ 0.000414 ┆ 0.00679 ┆ 0.41679 ┆ 1.51708 ┆ -0.1542 ┆ -0.0529 ┆ 0.51266 ┆ 5.69728 ┆ [-0.010 ┆ -6.2604 │
│         ┆ g_return ┆ g_return ┆          ┆          ┆          ┆ 1        ┆          ┆ 9        ┆          ┆ 9       ┆ 1       ┆ 6       ┆ 43      ┆ 19      ┆ 4       ┆         ┆ 31838   ┆ 7767582 │
│         ┆ _lag_1,c ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ -0.0149 ┆ 3495e-0 │
│         ┆ lose_log ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆ 2931]   ┆ 5       │
│         ┆ _return_ ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
│         ┆ lag_4    ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         ┆         │
└─────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴──────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┴─────────┘

In [39]:
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
plt.plot(btc_model_trades['equity_curve_net_taker'], label='BTCUSDT')
plt.plot(eth_model_trades['equity_curve_net_taker'], label='ETHUSDT')
plt.title('Net (after taker fees) Equity Curve: BTCUSDT vs ETHUSDT')
plt.xlabel('Trade #')
plt.ylabel('Cumulative Log Return')
plt.legend()
plt.tight_layout()
plt.show()

/var/folders/69/1t3g51kj5y96vspv1zh9f1x40000gn/T/ipykernel_30504/3784748504.py:11: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

# Part 4: Statistical Verdict — Is Any of This Actually Useful?

The equity curves and Sharpe ratios earlier in this notebook (the "Benchmark Linear Models" sections) were picked by scanning many feature combinations and keeping the best one — that number alone doesn't prove skill, since the best of many random tries tends to look good even with zero real edge.

This section pulls together the walk-forward *out-of-sample* results for both symbols and checks each one against two bars it has to clear to be called "useful":
1. Beat buy-and-hold (otherwise just holding the asset was better than trading it).
2. Beat the random-signal null distribution by a wide enough margin that the p-value is small (otherwise a coin flip could have produced the same result).

In [40]:
verdict = pl.DataFrame([
    {
        'sym': 'BTCUSDT',
        'oos_sharpe': btc_oos_perf['sharpe'],
        'buy_and_hold_sharpe': btc_bh_perf['sharpe'],
        'beats_buy_and_hold': btc_oos_perf['sharpe'] > btc_bh_perf['sharpe'],
        'random_null_mean_sharpe': btc_null_sharpes.mean(),
        'p_value': btc_p_value,
        'statistically_significant_p<0.05': btc_p_value < 0.05,
    },
    {
        'sym': 'ETHUSDT',
        'oos_sharpe': eth_oos_perf['sharpe'],
        'buy_and_hold_sharpe': eth_bh_perf['sharpe'],
        'beats_buy_and_hold': eth_oos_perf['sharpe'] > eth_bh_perf['sharpe'],
        'random_null_mean_sharpe': eth_null_sharpes.mean(),
        'p_value': eth_p_value,
        'statistically_significant_p<0.05': eth_p_value < 0.05,
    },
])
verdict

shape: (2, 7)
┌─────────┬────────────┬─────────────────────┬────────────────────┬─────────────────────────┬─────────┬──────────────────────────────────┐
│ sym     ┆ oos_sharpe ┆ buy_and_hold_sharpe ┆ beats_buy_and_hold ┆ random_null_mean_sharpe ┆ p_value ┆ statistically_significant_p<0.05 │
│ ---     ┆ ---        ┆ ---                 ┆ ---                ┆ ---                     ┆ ---     ┆ ---                              │
│ str     ┆ f64        ┆ f64                 ┆ i64                ┆ f64                     ┆ f64     ┆ bool                             │
╞═════════╪════════════╪═════════════════════╪════════════════════╪═════════════════════════╪═════════╪══════════════════════════════════╡
│ BTCUSDT ┆ 2.990813   ┆ -1.820758           ┆ 1                  ┆ -0.065437               ┆ 0.068   ┆ false                            │
│ ETHUSDT ┆ -0.007089  ┆ -2.229145           ┆ 1                  ┆ -0.003245               ┆ 0.489   ┆ false                            │
└─────────┴────────────┴─────────────────────┴────────────────────┴─────────────────────────┴─────────┴──────────────────────────────────┘

In [41]:
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

for ax, sym_label, null_sharpes, actual_sharpe, p in [
    (axes[0], 'BTCUSDT', btc_null_sharpes, btc_oos_perf['sharpe'], btc_p_value),
    (axes[1], 'ETHUSDT', eth_null_sharpes, eth_oos_perf['sharpe'], eth_p_value),
]:
    ax.hist(null_sharpes, bins=40, alpha=0.7, label='Random-signal null distribution')
    ax.axvline(actual_sharpe, color='red', linewidth=2, label=f'Model OOS Sharpe ({actual_sharpe:.2f})')
    ax.set_title(f'{sym_label}: Model Sharpe vs Chance (p={p:.3f})')
    ax.set_xlabel('Sharpe Ratio')
    ax.set_ylabel('Count')
    ax.legend()

plt.tight_layout()
plt.show()

/var/folders/69/1t3g51kj5y96vspv1zh9f1x40000gn/T/ipykernel_30504/637782495.py:15: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()